// Canadian NAICS 2022 — curated 6-digit codes grouped by sector.
// Not exhaustive; covers the codes most commonly selected by small and mid-sized
// businesses incorporating in Canada. Extend this list as needed — the UI reads
// from NAICS_CODES and displays code + title in a searchable combobox.

export type NaicsCode = {
  code: string;
  title: string;
  sector: string;
};

export const NAICS_CODES: NaicsCode[] = [
  // 11 — Agriculture, Forestry, Fishing and Hunting
  { code: "111110", title: "Soybean farming", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111140", title: "Wheat farming", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111211", title: "Potato farming", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111219", title: "Other vegetable (except potato) and melon farming", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111310", title: "Orange groves", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111411", title: "Mushroom production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111419", title: "Other food crops grown under cover", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111421", title: "Nursery and tree production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "111422", title: "Floriculture production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "112110", title: "Beef cattle ranching and farming, including feedlots", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "112120", title: "Dairy cattle and milk production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "112310", title: "Chicken egg production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "112320", title: "Broiler and other meat-type chicken production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "112510", title: "Aquaculture", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "113110", title: "Timber tract operations", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "113210", title: "Forest nurseries and gathering of forest products", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "113311", title: "Logging (except contract)", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "114113", title: "Salt water fishing", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "114114", title: "Freshwater fishing", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "115110", title: "Support activities for crop production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "115210", title: "Support activities for animal production", sector: "Agriculture, Forestry, Fishing and Hunting" },
  { code: "115310", title: "Support activities for forestry", sector: "Agriculture, Forestry, Fishing and Hunting" },

  // 21 — Mining, Quarrying, and Oil and Gas Extraction
  { code: "211110", title: "Oil and gas extraction", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212114", title: "Bituminous coal mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212210", title: "Iron ore mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212220", title: "Gold and silver ore mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212231", title: "Lead-zinc ore mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212299", title: "All other metal ore mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212314", title: "Granite mining and quarrying", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "212323", title: "Sand, gravel, clay, and ceramic and refractory minerals mining and quarrying", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "213111", title: "Oil and gas contract drilling", sector: "Mining, Quarrying, and Oil and Gas Extraction" },
  { code: "213119", title: "Other support activities for mining", sector: "Mining, Quarrying, and Oil and Gas Extraction" },

  // 22 — Utilities
  { code: "221111", title: "Hydro-electric power generation", sector: "Utilities" },
  { code: "221112", title: "Fossil-fuel electric power generation", sector: "Utilities" },
  { code: "221113", title: "Nuclear electric power generation", sector: "Utilities" },
  { code: "221119", title: "Other electric power generation (including solar, wind)", sector: "Utilities" },
  { code: "221121", title: "Electric bulk power transmission and control", sector: "Utilities" },
  { code: "221210", title: "Natural gas distribution", sector: "Utilities" },
  { code: "221310", title: "Water supply and irrigation systems", sector: "Utilities" },
  { code: "221320", title: "Sewage treatment facilities", sector: "Utilities" },
  { code: "221330", title: "Steam and air-conditioning supply", sector: "Utilities" },

  // 23 — Construction
  { code: "236110", title: "Residential building construction", sector: "Construction" },
  { code: "236210", title: "Industrial building and structure construction", sector: "Construction" },
  { code: "236220", title: "Commercial and institutional building construction", sector: "Construction" },
  { code: "237110", title: "Water and sewer line and related structures construction", sector: "Construction" },
  { code: "237120", title: "Oil and gas pipeline and related structures construction", sector: "Construction" },
  { code: "237130", title: "Power and communication line construction", sector: "Construction" },
  { code: "237210", title: "Land subdivision", sector: "Construction" },
  { code: "237310", title: "Highway, street and bridge construction", sector: "Construction" },
  { code: "238110", title: "Poured concrete foundation and structure contractors", sector: "Construction" },
  { code: "238120", title: "Structural steel and precast concrete contractors", sector: "Construction" },
  { code: "238130", title: "Framing contractors", sector: "Construction" },
  { code: "238140", title: "Masonry contractors", sector: "Construction" },
  { code: "238150", title: "Glass and glazing contractors", sector: "Construction" },
  { code: "238160", title: "Roofing contractors", sector: "Construction" },
  { code: "238210", title: "Electrical contractors and other wiring installation contractors", sector: "Construction" },
  { code: "238220", title: "Plumbing, heating and air-conditioning contractors", sector: "Construction" },
  { code: "238310", title: "Drywall and insulation contractors", sector: "Construction" },
  { code: "238320", title: "Painting and wall covering contractors", sector: "Construction" },
  { code: "238330", title: "Flooring contractors", sector: "Construction" },
  { code: "238350", title: "Finish carpentry contractors", sector: "Construction" },
  { code: "238910", title: "Site preparation contractors", sector: "Construction" },
  { code: "238990", title: "All other specialty trade contractors", sector: "Construction" },

  // 31-33 — Manufacturing
  { code: "311110", title: "Animal food manufacturing", sector: "Manufacturing" },
  { code: "311230", title: "Breakfast cereal manufacturing", sector: "Manufacturing" },
  { code: "311310", title: "Sugar manufacturing", sector: "Manufacturing" },
  { code: "311411", title: "Frozen fruit, juice and vegetable manufacturing", sector: "Manufacturing" },
  { code: "311420", title: "Fruit and vegetable canning, pickling and drying", sector: "Manufacturing" },
  { code: "311511", title: "Fluid milk manufacturing", sector: "Manufacturing" },
  { code: "311611", title: "Animal slaughtering (except poultry)", sector: "Manufacturing" },
  { code: "311811", title: "Retail bakeries", sector: "Manufacturing" },
  { code: "311814", title: "Commercial bakeries and frozen bakery product manufacturing", sector: "Manufacturing" },
  { code: "311911", title: "Roasted nut and peanut butter manufacturing", sector: "Manufacturing" },
  { code: "312120", title: "Breweries", sector: "Manufacturing" },
  { code: "312130", title: "Wineries", sector: "Manufacturing" },
  { code: "312140", title: "Distilleries", sector: "Manufacturing" },
  { code: "313110", title: "Fibre, yarn and thread mills", sector: "Manufacturing" },
  { code: "315110", title: "Hosiery and sock mills", sector: "Manufacturing" },
  { code: "315210", title: "Cut and sew clothing contracting", sector: "Manufacturing" },
  { code: "315280", title: "Other cut and sew clothing manufacturing", sector: "Manufacturing" },
  { code: "321111", title: "Sawmills (except shingle and shake mills)", sector: "Manufacturing" },
  { code: "321216", title: "Particle board and fibreboard mills", sector: "Manufacturing" },
  { code: "322122", title: "Newsprint mills", sector: "Manufacturing" },
  { code: "323113", title: "Commercial screen printing", sector: "Manufacturing" },
  { code: "323119", title: "Other printing", sector: "Manufacturing" },
  { code: "324110", title: "Petroleum refineries", sector: "Manufacturing" },
  { code: "325110", title: "Petrochemical manufacturing", sector: "Manufacturing" },
  { code: "325410", title: "Pharmaceutical and medicine manufacturing", sector: "Manufacturing" },
  { code: "326150", title: "Urethane and other foam product (except polystyrene) manufacturing", sector: "Manufacturing" },
  { code: "331110", title: "Iron and steel mills and ferro-alloy manufacturing", sector: "Manufacturing" },
  { code: "332311", title: "Prefabricated metal building and component manufacturing", sector: "Manufacturing" },
  { code: "333110", title: "Agricultural implement manufacturing", sector: "Manufacturing" },
  { code: "333310", title: "Commercial and service industry machinery manufacturing", sector: "Manufacturing" },
  { code: "334110", title: "Computer and peripheral equipment manufacturing", sector: "Manufacturing" },
  { code: "334210", title: "Telephone apparatus manufacturing", sector: "Manufacturing" },
  { code: "334510", title: "Electromedical and electrotherapeutic apparatus manufacturing", sector: "Manufacturing" },
  { code: "335110", title: "Electric lamp bulb and part manufacturing", sector: "Manufacturing" },
  { code: "336110", title: "Automobile and light-duty motor vehicle manufacturing", sector: "Manufacturing" },
  { code: "336390", title: "Other motor vehicle parts manufacturing", sector: "Manufacturing" },
  { code: "337110", title: "Wood kitchen cabinet and counter top manufacturing", sector: "Manufacturing" },
  { code: "337213", title: "Office furniture (except wood) manufacturing", sector: "Manufacturing" },
  { code: "339910", title: "Jewellery and silverware manufacturing", sector: "Manufacturing" },
  { code: "339920", title: "Sporting and athletic goods manufacturing", sector: "Manufacturing" },

  // 41 — Wholesale Trade
  { code: "411110", title: "Live animal merchant wholesalers", sector: "Wholesale Trade" },
  { code: "412110", title: "Petroleum and petroleum products merchant wholesalers", sector: "Wholesale Trade" },
  { code: "413110", title: "General-line food merchant wholesalers", sector: "Wholesale Trade" },
  { code: "414110", title: "Clothing and clothing accessories merchant wholesalers", sector: "Wholesale Trade" },
  { code: "415110", title: "New and used motor vehicle merchant wholesalers", sector: "Wholesale Trade" },
  { code: "416110", title: "Electrical wiring and construction supplies merchant wholesalers", sector: "Wholesale Trade" },
  { code: "417110", title: "Farm, lawn and garden machinery and equipment merchant wholesalers", sector: "Wholesale Trade" },
  { code: "417310", title: "Computer, computer peripheral and pre-packaged software merchant wholesalers", sector: "Wholesale Trade" },
  { code: "418110", title: "Recyclable metal merchant wholesalers", sector: "Wholesale Trade" },
  { code: "418990", title: "All other miscellaneous merchant wholesalers", sector: "Wholesale Trade" },
  { code: "419110", title: "Business-to-business electronic markets", sector: "Wholesale Trade" },

  // 44-45 — Retail Trade
  { code: "441110", title: "New car dealers", sector: "Retail Trade" },
  { code: "441120", title: "Used car dealers", sector: "Retail Trade" },
  { code: "441210", title: "Recreational vehicle dealers", sector: "Retail Trade" },
  { code: "441310", title: "Automotive parts and accessories stores", sector: "Retail Trade" },
  { code: "442110", title: "Furniture stores", sector: "Retail Trade" },
  { code: "443144", title: "Electronics and appliance stores", sector: "Retail Trade" },
  { code: "444110", title: "Home centres", sector: "Retail Trade" },
  { code: "444130", title: "Hardware stores", sector: "Retail Trade" },
  { code: "445110", title: "Supermarkets and other grocery (except convenience) stores", sector: "Retail Trade" },
  { code: "445120", title: "Convenience stores", sector: "Retail Trade" },
  { code: "445210", title: "Meat markets", sector: "Retail Trade" },
  { code: "445310", title: "Beer, wine and liquor stores", sector: "Retail Trade" },
  { code: "446110", title: "Pharmacies and drug stores", sector: "Retail Trade" },
  { code: "447110", title: "Gasoline stations with convenience stores", sector: "Retail Trade" },
  { code: "448110", title: "Men's clothing stores", sector: "Retail Trade" },
  { code: "448120", title: "Women's clothing stores", sector: "Retail Trade" },
  { code: "448140", title: "Family clothing stores", sector: "Retail Trade" },
  { code: "448210", title: "Shoe stores", sector: "Retail Trade" },
  { code: "448310", title: "Jewellery stores", sector: "Retail Trade" },
  { code: "451110", title: "Sporting goods stores", sector: "Retail Trade" },
  { code: "451120", title: "Hobby, toy and game stores", sector: "Retail Trade" },
  { code: "451310", title: "Book stores and news dealers", sector: "Retail Trade" },
  { code: "452110", title: "Department stores", sector: "Retail Trade" },
  { code: "452910", title: "Warehouse clubs and supercentres", sector: "Retail Trade" },
  { code: "453110", title: "Florists", sector: "Retail Trade" },
  { code: "453210", title: "Office supplies and stationery stores", sector: "Retail Trade" },
  { code: "453310", title: "Used merchandise stores", sector: "Retail Trade" },
  { code: "453910", title: "Pet and pet supplies stores", sector: "Retail Trade" },
  { code: "453920", title: "Art dealers", sector: "Retail Trade" },
  { code: "454110", title: "Electronic shopping and mail-order houses", sector: "Retail Trade" },
  { code: "454310", title: "Fuel dealers", sector: "Retail Trade" },

  // 48-49 — Transportation and Warehousing
  { code: "481110", title: "Scheduled air transportation", sector: "Transportation and Warehousing" },
  { code: "482112", title: "Short-haul freight rail transportation", sector: "Transportation and Warehousing" },
  { code: "483115", title: "Deep sea, coastal and Great Lakes water transportation (except by ferries)", sector: "Transportation and Warehousing" },
  { code: "484110", title: "General freight trucking, local", sector: "Transportation and Warehousing" },
  { code: "484121", title: "General freight trucking, long distance, truckload", sector: "Transportation and Warehousing" },
  { code: "484210", title: "Used household and office goods moving", sector: "Transportation and Warehousing" },
  { code: "485110", title: "Urban transit systems", sector: "Transportation and Warehousing" },
  { code: "485310", title: "Taxi service", sector: "Transportation and Warehousing" },
  { code: "485320", title: "Limousine service", sector: "Transportation and Warehousing" },
  { code: "485410", title: "School and employee bus transportation", sector: "Transportation and Warehousing" },
  { code: "488210", title: "Support activities for rail transportation", sector: "Transportation and Warehousing" },
  { code: "488490", title: "Other support activities for road transportation", sector: "Transportation and Warehousing" },
  { code: "488511", title: "Marine cargo handling", sector: "Transportation and Warehousing" },
  { code: "491110", title: "Postal service", sector: "Transportation and Warehousing" },
  { code: "492110", title: "Couriers", sector: "Transportation and Warehousing" },
  { code: "492210", title: "Local messengers and local delivery", sector: "Transportation and Warehousing" },
  { code: "493110", title: "General warehousing and storage", sector: "Transportation and Warehousing" },
  { code: "493120", title: "Refrigerated warehousing and storage", sector: "Transportation and Warehousing" },

  // 51 — Information and Cultural Industries
  { code: "511110", title: "Newspaper publishers", sector: "Information and Cultural Industries" },
  { code: "511120", title: "Periodical publishers", sector: "Information and Cultural Industries" },
  { code: "511130", title: "Book publishers", sector: "Information and Cultural Industries" },
  { code: "511210", title: "Software publishers", sector: "Information and Cultural Industries" },
  { code: "512110", title: "Motion picture and video production", sector: "Information and Cultural Industries" },
  { code: "512120", title: "Motion picture and video distribution", sector: "Information and Cultural Industries" },
  { code: "512190", title: "Post-production and other motion picture and video industries", sector: "Information and Cultural Industries" },
  { code: "512230", title: "Music publishers", sector: "Information and Cultural Industries" },
  { code: "512240", title: "Sound recording studios", sector: "Information and Cultural Industries" },
  { code: "515110", title: "Radio broadcasting", sector: "Information and Cultural Industries" },
  { code: "515120", title: "Television broadcasting", sector: "Information and Cultural Industries" },
  { code: "517111", title: "Wired telecommunications carriers (except cable)", sector: "Information and Cultural Industries" },
  { code: "517210", title: "Wireless telecommunications carriers (except satellite)", sector: "Information and Cultural Industries" },
  { code: "518210", title: "Data processing, hosting, and related services", sector: "Information and Cultural Industries" },
  { code: "519110", title: "News syndicates", sector: "Information and Cultural Industries" },
  { code: "519130", title: "Internet publishing and broadcasting and web search portals", sector: "Information and Cultural Industries" },

  // 52 — Finance and Insurance
  { code: "521110", title: "Monetary authorities — central bank", sector: "Finance and Insurance" },
  { code: "522111", title: "Personal and commercial banking industry", sector: "Finance and Insurance" },
  { code: "522130", title: "Local credit unions", sector: "Finance and Insurance" },
  { code: "522210", title: "Credit card issuing", sector: "Finance and Insurance" },
  { code: "522220", title: "Sales financing", sector: "Finance and Insurance" },
  { code: "522291", title: "Consumer lending", sector: "Finance and Insurance" },
  { code: "522310", title: "Mortgage and non-mortgage loan brokers", sector: "Finance and Insurance" },
  { code: "523110", title: "Investment banking and securities dealing", sector: "Finance and Insurance" },
  { code: "523120", title: "Securities brokerage", sector: "Finance and Insurance" },
  { code: "523930", title: "Investment advice", sector: "Finance and Insurance" },
  { code: "524111", title: "Direct individual life, health and medical insurance carriers", sector: "Finance and Insurance" },
  { code: "524210", title: "Insurance agencies and brokerages", sector: "Finance and Insurance" },
  { code: "526111", title: "Trusteed pension funds", sector: "Finance and Insurance" },

  // 53 — Real Estate and Rental and Leasing
  { code: "531111", title: "Lessors of residential buildings and dwellings", sector: "Real Estate and Rental and Leasing" },
  { code: "531120", title: "Lessors of non-residential buildings (except mini-warehouses)", sector: "Real Estate and Rental and Leasing" },
  { code: "531190", title: "Lessors of other real estate property", sector: "Real Estate and Rental and Leasing" },
  { code: "531211", title: "Real estate agents", sector: "Real Estate and Rental and Leasing" },
  { code: "531212", title: "Offices of real estate brokers", sector: "Real Estate and Rental and Leasing" },
  { code: "531310", title: "Real estate property managers", sector: "Real Estate and Rental and Leasing" },
  { code: "531320", title: "Offices of real estate appraisers", sector: "Real Estate and Rental and Leasing" },
  { code: "532111", title: "Passenger car rental", sector: "Real Estate and Rental and Leasing" },
  { code: "532112", title: "Passenger car leasing", sector: "Real Estate and Rental and Leasing" },
  { code: "532120", title: "Truck, utility trailer and RV (recreational vehicle) rental and leasing", sector: "Real Estate and Rental and Leasing" },
  { code: "532210", title: "Consumer electronics and appliance rental", sector: "Real Estate and Rental and Leasing" },
  { code: "532280", title: "All other consumer goods rental", sector: "Real Estate and Rental and Leasing" },
  { code: "533110", title: "Lessors of non-financial intangible assets (except copyrighted works)", sector: "Real Estate and Rental and Leasing" },

  // 54 — Professional, Scientific and Technical Services
  { code: "541110", title: "Offices of lawyers", sector: "Professional, Scientific and Technical Services" },
  { code: "541120", title: "Offices of notaries", sector: "Professional, Scientific and Technical Services" },
  { code: "541190", title: "Other legal services", sector: "Professional, Scientific and Technical Services" },
  { code: "541212", title: "Offices of accountants", sector: "Professional, Scientific and Technical Services" },
  { code: "541213", title: "Tax preparation services", sector: "Professional, Scientific and Technical Services" },
  { code: "541214", title: "Payroll services", sector: "Professional, Scientific and Technical Services" },
  { code: "541215", title: "Bookkeeping, payroll and related services", sector: "Professional, Scientific and Technical Services" },
  { code: "541310", title: "Architectural services", sector: "Professional, Scientific and Technical Services" },
  { code: "541320", title: "Landscape architectural services", sector: "Professional, Scientific and Technical Services" },
  { code: "541330", title: "Engineering services", sector: "Professional, Scientific and Technical Services" },
  { code: "541340", title: "Drafting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541350", title: "Building inspection services", sector: "Professional, Scientific and Technical Services" },
  { code: "541360", title: "Geophysical surveying and mapping services", sector: "Professional, Scientific and Technical Services" },
  { code: "541370", title: "Surveying and mapping (except geophysical) services", sector: "Professional, Scientific and Technical Services" },
  { code: "541380", title: "Testing laboratories", sector: "Professional, Scientific and Technical Services" },
  { code: "541410", title: "Interior design services", sector: "Professional, Scientific and Technical Services" },
  { code: "541420", title: "Industrial design services", sector: "Professional, Scientific and Technical Services" },
  { code: "541430", title: "Graphic design services", sector: "Professional, Scientific and Technical Services" },
  { code: "541490", title: "Other specialized design services", sector: "Professional, Scientific and Technical Services" },
  { code: "541510", title: "Computer systems design and related services", sector: "Professional, Scientific and Technical Services" },
  { code: "541611", title: "Administrative management and general management consulting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541612", title: "Human resources consulting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541619", title: "Other management consulting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541620", title: "Environmental consulting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541690", title: "Other scientific and technical consulting services", sector: "Professional, Scientific and Technical Services" },
  { code: "541710", title: "Research and development in the physical, engineering and life sciences", sector: "Professional, Scientific and Technical Services" },
  { code: "541720", title: "Research and development in the social sciences and humanities", sector: "Professional, Scientific and Technical Services" },
  { code: "541810", title: "Advertising agencies", sector: "Professional, Scientific and Technical Services" },
  { code: "541820", title: "Public relations services", sector: "Professional, Scientific and Technical Services" },
  { code: "541830", title: "Media buying agencies", sector: "Professional, Scientific and Technical Services" },
  { code: "541850", title: "Display advertising", sector: "Professional, Scientific and Technical Services" },
  { code: "541860", title: "Direct mail advertising", sector: "Professional, Scientific and Technical Services" },
  { code: "541870", title: "Advertising material distribution services", sector: "Professional, Scientific and Technical Services" },
  { code: "541890", title: "Other services related to advertising", sector: "Professional, Scientific and Technical Services" },
  { code: "541910", title: "Marketing research and public opinion polling", sector: "Professional, Scientific and Technical Services" },
  { code: "541921", title: "Photography studios, portrait", sector: "Professional, Scientific and Technical Services" },
  { code: "541922", title: "Commercial photography", sector: "Professional, Scientific and Technical Services" },
  { code: "541930", title: "Translation and interpretation services", sector: "Professional, Scientific and Technical Services" },
  { code: "541940", title: "Veterinary services", sector: "Professional, Scientific and Technical Services" },
  { code: "541990", title: "All other professional, scientific and technical services", sector: "Professional, Scientific and Technical Services" },

  // 55 — Management of Companies and Enterprises
  { code: "551113", title: "Holding companies", sector: "Management of Companies and Enterprises" },
  { code: "551114", title: "Head offices", sector: "Management of Companies and Enterprises" },

  // 56 — Administrative and Support, Waste Management and Remediation Services
  { code: "561110", title: "Office administrative services", sector: "Administrative and Support Services" },
  { code: "561210", title: "Facilities support services", sector: "Administrative and Support Services" },
  { code: "561310", title: "Employment placement agencies and executive search services", sector: "Administrative and Support Services" },
  { code: "561320", title: "Temporary help services", sector: "Administrative and Support Services" },
  { code: "561410", title: "Document preparation services", sector: "Administrative and Support Services" },
  { code: "561420", title: "Telephone call centres", sector: "Administrative and Support Services" },
  { code: "561430", title: "Business service centres", sector: "Administrative and Support Services" },
  { code: "561440", title: "Collection agencies", sector: "Administrative and Support Services" },
  { code: "561450", title: "Credit bureaus", sector: "Administrative and Support Services" },
  { code: "561490", title: "Other business support services", sector: "Administrative and Support Services" },
  { code: "561510", title: "Travel agencies", sector: "Administrative and Support Services" },
  { code: "561520", title: "Tour operators", sector: "Administrative and Support Services" },
  { code: "561611", title: "Investigation services", sector: "Administrative and Support Services" },
  { code: "561612", title: "Security guards and patrol services", sector: "Administrative and Support Services" },
  { code: "561621", title: "Security systems services (except locksmiths)", sector: "Administrative and Support Services" },
  { code: "561710", title: "Exterminating and pest control services", sector: "Administrative and Support Services" },
  { code: "561722", title: "Janitorial services (except window cleaning)", sector: "Administrative and Support Services" },
  { code: "561730", title: "Landscaping services", sector: "Administrative and Support Services" },
  { code: "561740", title: "Carpet and upholstery cleaning services", sector: "Administrative and Support Services" },
  { code: "561790", title: "Other services to buildings and dwellings", sector: "Administrative and Support Services" },
  { code: "561910", title: "Packaging and labelling services", sector: "Administrative and Support Services" },
  { code: "562110", title: "Waste collection", sector: "Administrative and Support Services" },
  { code: "562210", title: "Waste treatment and disposal", sector: "Administrative and Support Services" },
  { code: "562910", title: "Remediation services", sector: "Administrative and Support Services" },

  // 61 — Educational Services
  { code: "611110", title: "Elementary and secondary schools", sector: "Educational Services" },
  { code: "611210", title: "Community colleges and C.E.G.E.P.s", sector: "Educational Services" },
  { code: "611310", title: "Universities", sector: "Educational Services" },
  { code: "611410", title: "Business and secretarial schools", sector: "Educational Services" },
  { code: "611420", title: "Computer training", sector: "Educational Services" },
  { code: "611430", title: "Professional and management development training", sector: "Educational Services" },
  { code: "611510", title: "Technical and trade schools", sector: "Educational Services" },
  { code: "611610", title: "Fine arts schools", sector: "Educational Services" },
  { code: "611620", title: "Sports and recreation instruction", sector: "Educational Services" },
  { code: "611630", title: "Language schools", sector: "Educational Services" },
  { code: "611691", title: "Exam preparation and tutoring", sector: "Educational Services" },
  { code: "611710", title: "Educational support services", sector: "Educational Services" },

  // 62 — Health Care and Social Assistance
  { code: "621110", title: "Offices of physicians", sector: "Health Care and Social Assistance" },
  { code: "621210", title: "Offices of dentists", sector: "Health Care and Social Assistance" },
  { code: "621310", title: "Offices of chiropractors", sector: "Health Care and Social Assistance" },
  { code: "621320", title: "Offices of optometrists", sector: "Health Care and Social Assistance" },
  { code: "621330", title: "Offices of mental health practitioners (except physicians)", sector: "Health Care and Social Assistance" },
  { code: "621340", title: "Offices of physical, occupational and speech therapists and audiologists", sector: "Health Care and Social Assistance" },
  { code: "621390", title: "Offices of all other health practitioners", sector: "Health Care and Social Assistance" },
  { code: "621410", title: "Family planning centres", sector: "Health Care and Social Assistance" },
  { code: "621420", title: "Out-patient mental health and substance abuse centres", sector: "Health Care and Social Assistance" },
  { code: "621494", title: "Community health centres", sector: "Health Care and Social Assistance" },
  { code: "621510", title: "Medical and diagnostic laboratories", sector: "Health Care and Social Assistance" },
  { code: "621610", title: "Home health care services", sector: "Health Care and Social Assistance" },
  { code: "622111", title: "General (except paediatric) hospitals", sector: "Health Care and Social Assistance" },
  { code: "623110", title: "Nursing care facilities", sector: "Health Care and Social Assistance" },
  { code: "623210", title: "Residential developmental handicap facilities", sector: "Health Care and Social Assistance" },
  { code: "623310", title: "Community care facilities for the elderly", sector: "Health Care and Social Assistance" },
  { code: "624110", title: "Child and youth services", sector: "Health Care and Social Assistance" },
  { code: "624120", title: "Services for the elderly and persons with disabilities", sector: "Health Care and Social Assistance" },
  { code: "624210", title: "Community food services", sector: "Health Care and Social Assistance" },
  { code: "624410", title: "Child day-care services", sector: "Health Care and Social Assistance" },

  // 71 — Arts, Entertainment and Recreation
  { code: "711110", title: "Theatre companies and dinner theatres", sector: "Arts, Entertainment and Recreation" },
  { code: "711120", title: "Dance companies", sector: "Arts, Entertainment and Recreation" },
  { code: "711130", title: "Musical groups and artists", sector: "Arts, Entertainment and Recreation" },
  { code: "711190", title: "Other performing arts companies", sector: "Arts, Entertainment and Recreation" },
  { code: "711213", title: "Horse race tracks", sector: "Arts, Entertainment and Recreation" },
  { code: "711319", title: "Other promoters of performing arts, sports and similar events", sector: "Arts, Entertainment and Recreation" },
  { code: "711410", title: "Agents and managers for artists, athletes, entertainers and other public figures", sector: "Arts, Entertainment and Recreation" },
  { code: "711511", title: "Independent artists, writers and performers", sector: "Arts, Entertainment and Recreation" },
  { code: "712111", title: "Non-commercial art museums and galleries", sector: "Arts, Entertainment and Recreation" },
  { code: "712115", title: "History and science museums", sector: "Arts, Entertainment and Recreation" },
  { code: "712120", title: "Historic and heritage sites", sector: "Arts, Entertainment and Recreation" },
  { code: "712130", title: "Zoos and botanical gardens", sector: "Arts, Entertainment and Recreation" },
  { code: "713110", title: "Amusement and theme parks", sector: "Arts, Entertainment and Recreation" },
  { code: "713210", title: "Casinos (except casino hotels)", sector: "Arts, Entertainment and Recreation" },
  { code: "713910", title: "Golf courses and country clubs", sector: "Arts, Entertainment and Recreation" },
  { code: "713920", title: "Skiing facilities", sector: "Arts, Entertainment and Recreation" },
  { code: "713940", title: "Fitness and recreational sports centres", sector: "Arts, Entertainment and Recreation" },
  { code: "713950", title: "Bowling centres", sector: "Arts, Entertainment and Recreation" },
  { code: "713990", title: "All other amusement and recreation industries", sector: "Arts, Entertainment and Recreation" },

  // 72 — Accommodation and Food Services
  { code: "721111", title: "Hotels", sector: "Accommodation and Food Services" },
  { code: "721113", title: "Resorts", sector: "Accommodation and Food Services" },
  { code: "721114", title: "Motor hotels", sector: "Accommodation and Food Services" },
  { code: "721120", title: "Casino hotels", sector: "Accommodation and Food Services" },
  { code: "721191", title: "Bed and breakfast", sector: "Accommodation and Food Services" },
  { code: "721198", title: "All other traveller accommodation", sector: "Accommodation and Food Services" },
  { code: "721211", title: "RV (recreational vehicle) parks and campgrounds", sector: "Accommodation and Food Services" },
  { code: "721310", title: "Rooming and boarding houses", sector: "Accommodation and Food Services" },
  { code: "722310", title: "Food service contractors", sector: "Accommodation and Food Services" },
  { code: "722320", title: "Caterers", sector: "Accommodation and Food Services" },
  { code: "722330", title: "Mobile food services", sector: "Accommodation and Food Services" },
  { code: "722410", title: "Drinking places (alcoholic beverages)", sector: "Accommodation and Food Services" },
  { code: "722511", title: "Full-service restaurants", sector: "Accommodation and Food Services" },
  { code: "722512", title: "Limited-service eating places", sector: "Accommodation and Food Services" },
  { code: "722513", title: "Limited-service eating places (non-chain)", sector: "Accommodation and Food Services" },

  // 81 — Other Services (except Public Administration)
  { code: "811111", title: "General automotive repair", sector: "Other Services" },
  { code: "811112", title: "Automotive exhaust system repair", sector: "Other Services" },
  { code: "811121", title: "Automotive body, paint and interior repair and maintenance", sector: "Other Services" },
  { code: "811192", title: "Car washes", sector: "Other Services" },
  { code: "811210", title: "Electronic and precision equipment repair and maintenance", sector: "Other Services" },
  { code: "811310", title: "Commercial and industrial machinery and equipment (except automotive and electronic) repair and maintenance", sector: "Other Services" },
  { code: "811412", title: "Appliance repair and maintenance", sector: "Other Services" },
  { code: "811490", title: "Other personal and household goods repair and maintenance", sector: "Other Services" },
  { code: "812114", title: "Barber shops", sector: "Other Services" },
  { code: "812115", title: "Beauty salons", sector: "Other Services" },
  { code: "812116", title: "Unisex hair salons", sector: "Other Services" },
  { code: "812190", title: "Other personal care services", sector: "Other Services" },
  { code: "812210", title: "Funeral homes", sector: "Other Services" },
  { code: "812310", title: "Coin-operated laundries and dry cleaners", sector: "Other Services" },
  { code: "812320", title: "Dry cleaning and laundry services (except coin-operated)", sector: "Other Services" },
  { code: "812910", title: "Pet care (except veterinary) services", sector: "Other Services" },
  { code: "812921", title: "Photo finishing laboratories (except one-hour)", sector: "Other Services" },
  { code: "812990", title: "All other personal services", sector: "Other Services" },
  { code: "813110", title: "Religious organizations", sector: "Other Services" },
  { code: "813210", title: "Grant-making and giving services", sector: "Other Services" },
  { code: "813310", title: "Social advocacy organizations", sector: "Other Services" },
  { code: "813410", title: "Civic and social organizations", sector: "Other Services" },
  { code: "813910", title: "Business associations", sector: "Other Services" },
  { code: "813930", title: "Labour organizations", sector: "Other Services" },
  { code: "813940", title: "Political organizations", sector: "Other Services" },
  { code: "813990", title: "Other membership organizations", sector: "Other Services" },
  { code: "814110", title: "Private households", sector: "Other Services" },

  // 91 — Public Administration
  { code: "911910", title: "Other federal government public administration", sector: "Public Administration" },
  { code: "912910", title: "Other provincial and territorial public administration", sector: "Public Administration" },
  { code: "913910", title: "Other local, municipal and regional public administration", sector: "Public Administration" },
];

export const NAICS_SECTORS = Array.from(new Set(NAICS_CODES.map((c) => c.sector)));

export function searchNaics(query: string, limit = 50): NaicsCode[] {
  const q = query.trim().toLowerCase();
  if (!q) return NAICS_CODES.slice(0, limit);
  const tokens = q.split(/\s+/).filter(Boolean);
  const scored: { code: NaicsCode; score: number }[] = [];
  for (const c of NAICS_CODES) {
    const hay = `${c.code} ${c.title} ${c.sector}`.toLowerCase();
    let score = 0;
    let missed = false;
    for (const t of tokens) {
      if (!hay.includes(t)) {
        missed = true;
        break;
      }
      if (c.code.startsWith(t)) score += 5;
      if (c.title.toLowerCase().startsWith(t)) score += 3;
      score += 1;
    }
    if (!missed) scored.push({ code: c, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.code);
}
