import type { ArticleSection } from "../articles";

export type ExpandedArticle = { readTime: string; content: ArticleSection[]; faq: { q: string; a: string }[] };

// Government fees verified on 2026-10-04 against:
//  - https://www.ontario.ca/page/cost-time-required-to-register-change-search-for-business-name-corporation-not-for-profit
//  - https://ised-isde.canada.ca/site/corporations-canada/en/services-fees-and-processing-times
// Keep in sync with src/lib/govFees.ts.

export const expanded: Record<"en" | "fr" | "es", ExpandedArticle> = {
  en: {
    readTime: "11 min read",
    content: [
      { type: "paragraph", text: "The Ontario government charges $300 to file Articles of Incorporation through the Ontario Business Registry, and the fee is the same whether you file online or by mail. That is the only government fee every Ontario corporation must pay. If you want a named corporation, you also need an Ontario-biased NUANS name search report, which you buy from a private search house. The Initial Return and the yearly annual return carry no government fee. Everything else, from a minute book to professional help, depends on the choices you make." },
      { type: "paragraph", text: "This guide sets out every cost in one place: what the government charges, what is optional, what you pay once and what you pay every year, and how the total compares with a federal incorporation. All government fees below were checked against the official Ontario and Corporations Canada fee schedules." },

      { type: "heading", id: "government-fee", text: "The government filing fee" },
      { type: "paragraph", text: "The core cost is the $300 fee to incorporate under the Ontario Business Corporations Act (OBCA). You pay it to the Ontario Business Registry when you file your Articles of Incorporation. Filed online, the incorporation is processed immediately. Filed by mail, ServiceOntario lists a processing time of about 15 business days. The fee does not change with the method, so most people file online." },
      { type: "paragraph", text: "There is no HST on the government filing fee itself. If you use a lawyer or an incorporation service, HST applies to their professional or service fee, not to the $300 the government collects. Ontario does not offer a paid express option for incorporation, because online filings are already immediate." },

      { type: "heading", id: "fee-breakdown", text: "Full fee breakdown" },
      { type: "paragraph", text: "Here is every cost an Ontario business corporation can expect around incorporation, including the filings that are free but still mandatory. The federal fee is included at the bottom for comparison." },
      {
        type: "table",
        head: ["Item", "Paid to", "Cost (CAD)", "When"],
        rows: [
          ["Articles of Incorporation (OBCA)", "Ontario Business Registry", "$300", "Once, at incorporation"],
          ["NUANS name search report (named corporation only)", "Private NUANS search house", "Set by the search house", "Once, dated within 90 days before filing"],
          ["Initial Return (Corporations Information Act)", "Ontario Business Registry", "$0", "Within 60 days of incorporation"],
          ["Annual return (Corporations Information Act)", "Ontario Business Registry", "$0", "Every year, within six months after fiscal year-end"],
          ["Business name registration (operating name)", "Ontario Business Registry", "$60", "Only if you operate under another name; renewed every five years"],
          ["Articles of Amendment", "Ontario Business Registry", "$150", "Only if you later change your articles"],
          ["Certificate of Status", "Ontario Business Registry", "$26", "Only when a bank, lender or buyer asks for one"],
          ["Corporate minute book", "Prepared by you or a provider", "No government fee", "Set up once, then kept current"],
          ["Business Number and GST/HST account", "Canada Revenue Agency", "$0", "When you register"],
          ["Federal Articles of Incorporation (CBCA), for comparison", "Corporations Canada", "$200", "Once, at incorporation"],
        ],
      },
      { type: "callout", title: "Fees change", text: "These are the official fees as published by ServiceOntario and Corporations Canada when this guide was last updated. Government fees are adjusted from time to time, so confirm the current schedule on the official site before you file." },

      { type: "heading", id: "named-vs-numbered", text: "Named vs numbered: the NUANS report" },
      { type: "paragraph", text: "If you want a named corporation (\"Maplewind Consulting Inc.\"), you need a NUANS name search report to confirm the name is available and not confusingly similar to an existing one. That report has its own cost. A numbered corporation (\"1234567 Ontario Inc.\") skips the NUANS step entirely, which is cheaper and faster, the trade-off being you have a number instead of a brand name until you register an operating name.", parts: ["If you want a named corporation (\"Maplewind Consulting Inc.\"), you need a ", { text: "NUANS name search report", href: "/nuans" }, " to confirm the name is available and not confusingly similar to an existing one. That report has its own cost. A numbered corporation (\"1234567 Ontario Inc.\") skips the NUANS step entirely, which is cheaper and faster, the trade-off being you have a number instead of a brand name until you register an operating name."] },
      { type: "paragraph", text: "Ontario has specific rules for the report. It must be Ontario-biased, because a federally biased report is not accepted for an Ontario filing, and it must be dated no more than 90 days before you file your articles. The Ontario government does not sell NUANS reports. You order one from a private search house, which sets its own price. If the name you want is refused or the report expires before you file, you pay for a new one, so it is worth understanding how a NUANS search works before ordering.", parts: ["Ontario has specific rules for the report. It must be Ontario-biased, because a federally biased report is not accepted for an Ontario filing, and it must be dated no more than 90 days before you file your articles. The Ontario government does not sell NUANS reports. You order one from a private search house, which sets its own price. If the name you want is refused or the report expires before you file, you pay for a new one, so it is worth ", { text: "understanding how a NUANS search works", href: "/guides/what-is-nuans-name-search" }, " before ordering."] },
      { type: "paragraph", text: "A numbered corporation that wants to trade under a brand can register that operating name under the Business Names Act for $60, renewed every five years. Some owners start numbered to save time and money, then decide on a name later. Our guide to named vs numbered corporations walks through that choice.", parts: ["A numbered corporation that wants to trade under a brand can register that operating name under the Business Names Act for $60, renewed every five years. Some owners start numbered to save time and money, then decide on a name later. Our guide to ", { text: "named vs numbered corporations", href: "/guides/named-vs-numbered-corporation" }, " walks through that choice."] },

      { type: "heading", id: "one-time-vs-ongoing", text: "One-time costs vs ongoing costs" },
      { type: "paragraph", text: "It helps to split the budget in two. One-time costs are paid to bring the corporation into existence and organize it properly:" },
      { type: "list", items: ["The $300 Articles of Incorporation fee.", "A NUANS report, if you choose a named corporation.", "Setting up the minute book: bylaws, organizational resolutions, share subscriptions and share certificates, and the corporate registers.", "The Initial Return, which has no government fee but must be filed within 60 days of incorporation.", "Any professional or service fee for preparing the documents and filing them."] },
      { type: "paragraph", text: "Ongoing costs come every year for as long as the corporation exists, whether or not it earns any revenue:" },
      { type: "list", items: ["The Ontario annual return, free to file but mandatory.", "The corporate (T2) income tax return, usually prepared by an accountant.", "Bookkeeping, which most corporations either do themselves with software or pay someone to handle.", "Annual resolutions of the directors and shareholders, kept in the minute book.", "A registered office or address service, if you use one instead of your own address.", "Business bank account fees, which vary by institution."] },
      { type: "paragraph", text: "The one-time costs are what most people compare when shopping for an incorporation. The ongoing costs are what actually determine whether incorporating makes financial sense, so look at both before deciding." },

      { type: "heading", id: "optional-costs", text: "Optional costs worth knowing about" },
      { type: "list", items: ["Minute book setup. Ontario corporations are legally required to keep one. You can assemble it yourself or have it prepared, which most owners find worth it.", "Registered office / address service. If you do not want your home address on the public record, an address service is an added cost.", "Professional help. A lawyer or incorporation service charges a fee on top of the government cost, in exchange for getting the share structure and documents right.", "Operating name registration. $60 if you trade under a name other than the corporation's legal name.", "Certificate of Status. $26 when a bank, landlord or lender asks for proof that the corporation is in good standing."] },
      { type: "paragraph", text: "The minute book deserves a closer look, because it is often the line item people cut to save money. The OBCA requires every corporation to keep records such as its articles, bylaws, minutes, resolutions and its registers of directors, shareholders and individuals with significant control. There is no government fee for it, but the documents still have to be drafted correctly. An initial minute book prepared at incorporation costs less than reconstructing one years later, when a bank, buyer or the CRA asks to see it. Our minute book guide explains what goes in it.", parts: ["The minute book deserves a closer look, because it is often the line item people cut to save money. The OBCA requires every corporation to keep records such as its articles, bylaws, minutes, resolutions and its registers of directors, shareholders and individuals with significant control. There is no government fee for it, but the documents still have to be drafted correctly. An ", { text: "initial minute book", href: "/services/initial-minute-book" }, " prepared at incorporation costs less than reconstructing one years later, when a bank, buyer or the CRA asks to see it. Our ", { text: "minute book guide", href: "/guides/corporate-minute-book" }, " explains what goes in it."] },
      { type: "paragraph", text: "The registered office is the other common add-on. An Ontario corporation must have a registered office at a physical address in Ontario, and that address appears on the public record. Many home-based owners prefer a registered office service so their home address stays private.", parts: ["The registered office is the other common add-on. An Ontario corporation must have a registered office at a physical address in Ontario, and that address appears on the public record. Many home-based owners prefer a ", { text: "registered office service", href: "/services/registered-office" }, " so their home address stays private."] },

      { type: "heading", id: "diy-vs-service", text: "Doing it yourself vs using a service" },
      { type: "paragraph", text: "There are three broad ways to incorporate in Ontario, and they sit at three different price levels." },
      { type: "paragraph", text: "Doing it yourself is the cheapest in cash terms. You file directly on the Ontario Business Registry and pay only the government fee, plus a NUANS report if you want a name. In exchange, you draft the articles, choose the share structure, prepare the bylaws and organizational resolutions, and build the minute book yourself. The registry accepts the articles you file; it does not review whether your share structure suits your business." },
      { type: "paragraph", text: "An online incorporation service costs more than doing it yourself but considerably less than a full-service law firm. A good service handles the filing, the name search, a share structure suited to common situations and the minute book, for a known price. Korporex incorporates Ontario and federal corporations online for a fixed price that includes the filing, name search, share structure, and minute book, with documents delivered within 24 hours.", parts: ["An online incorporation service costs more than doing it yourself but considerably less than a full-service law firm. A good service handles the filing, the name search, a share structure suited to common situations and the minute book, for a known price. Korporex incorporates Ontario and federal corporations online ", { text: "for a fixed price", href: "/order" }, " that includes the filing, name search, share structure, and minute book, with documents delivered within 24 hours."] },
      { type: "paragraph", text: "A lawyer is the most expensive route and the right one when the situation is not standard: several founders who need a shareholder agreement, outside investors, a holding company structure, a professional corporation, or tax planning that depends on the share classes. Fees vary widely with the work involved, so ask for a written quote that separates the government fees, the NUANS report and the legal fees." },
      { type: "callout", title: "Compare like with like", text: "When comparing quotes, check whether the price includes the $300 government fee, the NUANS report, the Initial Return and a complete minute book. A low headline price that leaves out the minute book or the Initial Return is not the cheaper option." },

      { type: "heading", id: "ongoing-costs", text: "What it costs each year after" },
      { type: "paragraph", text: "Incorporating is not a one-time cost. Each year an Ontario corporation files an annual return and a separate corporate (T2) tax return, and keeps its minute book current. Budget for the corporate tax filing in particular, since it usually means an accountant.", parts: ["Incorporating is not a one-time cost. Each year an Ontario corporation files an ", { text: "annual return", href: "/guides/corporate-annual-returns-canada" }, " and a separate corporate (T2) tax return, and keeps its minute book current. Budget for the corporate tax filing in particular, since it usually means an accountant."] },
      { type: "paragraph", text: "The Ontario annual return is filed on the Ontario Business Registry within six months after the end of the corporation's fiscal year. There is no government fee, but it is not optional: a corporation that stops filing can eventually be dissolved. If you would rather not track the deadline, an Ontario annual return filing service can handle it. The T2 return goes to the Canada Revenue Agency, and the CRA also administers Ontario corporate income tax, so one T2 covers both. Because corporate tax returns and financial statements are more involved than a personal return, accounting fees are usually the largest recurring cost of running a corporation.", parts: ["The Ontario annual return is filed on the Ontario Business Registry within six months after the end of the corporation's fiscal year. There is no government fee, but it is not optional: a corporation that stops filing can eventually be dissolved. If you would rather not track the deadline, an ", { text: "Ontario annual return filing service", href: "/services/annual-return-on" }, " can handle it. The T2 return goes to the Canada Revenue Agency, and the CRA also administers Ontario corporate income tax, so one T2 covers both. Because corporate tax returns and financial statements are more involved than a personal return, accounting fees are usually the largest recurring cost of running a corporation."] },
      { type: "paragraph", text: "The minute book also needs yearly upkeep. Directors approve the financial statements, shareholders deal with the auditor or pass a resolution waiving one where the law allows it, and directors and officers are confirmed. These annual resolutions cost nothing to file because they are not filed anywhere, but they need to be prepared and signed." },

      { type: "heading", id: "hidden-costs", text: "Costs people forget to budget for" },
      { type: "list", items: ["Late filings. The annual return has no fee, but missing it can lead to dissolution, and reviving a dissolved corporation costs far more than filing on time. The CRA charges penalties and interest on a late T2 when tax is owing.", "Changes after incorporation. Changing the corporation's name or share structure means Articles of Amendment, which carry a $150 government fee, plus a new NUANS report for a name change.", "Fixing a poor share structure. A structure that does not fit your plans can be costly to restructure later, once there are shareholders, investors or tax planning to work around.", "Keeping the public record current. Changes to directors or the registered office are reported with a Notice of Change. The government fee is $0, but someone has to file it.", "Banking. Business accounts usually carry monthly fees, and banks often ask for the articles, the minute book and sometimes a Certificate of Status ($26) to open one."] },
      { type: "paragraph", text: "None of these are large on their own. Together they are why the true cost of a corporation is better measured over the first few years than on the day you file." },

      { type: "heading", id: "ontario-vs-federal", text: "Ontario vs federal: cost comparison" },
      { type: "paragraph", text: "A federal corporation under the Canada Business Corporations Act (CBCA) is cheaper to file, but the comparison does not stop at the filing fee. Here is how the two compare side by side." },
      {
        type: "table",
        head: ["Cost item", "Ontario (OBCA)", "Federal (CBCA)"],
        rows: [
          ["Incorporation filing fee", "$300", "$200"],
          ["Name search", "Ontario-biased NUANS report required for a named corporation, bought from a search house", "No separate NUANS report needed online with a word name; the name search is part of the federal process"],
          ["Express processing", "Not offered; online filing is immediate", "$100 optional, four business hours"],
          ["Annual return", "$0, filed with the Ontario Business Registry", "$12, filed with Corporations Canada"],
          ["Articles of Amendment", "$150", "$200 (some amendments are free)"],
          ["Operating in Ontario", "Nothing more to file", "Ontario Initial Return within 60 days of starting business in Ontario, $0"],
          ["Name protection", "Ontario", "Across Canada"],
        ],
      },
      { type: "paragraph", text: "On fees alone, a federal corporation costs less to create, and federal incorporation includes the name search for a word name. A federal corporation that carries on business in Ontario must still file an Initial Return with Ontario and keep its Ontario information current, and it pays a $12 federal annual return each year. If your business will operate only in Ontario, the Ontario route is simpler to maintain. If you expect to operate across Canada or want national name protection, the federal route is often worth it. Our guide to federal vs provincial incorporation covers the trade-offs beyond cost.", parts: ["On fees alone, a federal corporation costs less to create, and federal incorporation includes the name search for a word name. A federal corporation that carries on business in Ontario must still file an ", { text: "Initial Return with Ontario", href: "/services/initial-return-on" }, " and keep its Ontario information current, and it pays a $12 ", { text: "federal annual return", href: "/services/annual-return-federal" }, " each year. If your business will operate only in Ontario, the Ontario route is simpler to maintain. If you expect to operate across Canada or want national name protection, the federal route is often worth it. Our guide to ", { text: "federal vs provincial incorporation", href: "/guides/federal-vs-provincial-incorporation" }, " covers the trade-offs beyond cost."] },

      { type: "heading", id: "extra-provincial", text: "Extra-provincial costs" },
      { type: "paragraph", text: "Extra-provincial registration applies when a corporation carries on business outside the jurisdiction where it was incorporated. An Ontario corporation that expands into another province has to register there, and each province sets its own fee and annual filing. A federal corporation must likewise register in each province where it operates, including Ontario." },
      { type: "paragraph", text: "Within Ontario, corporations from other provinces and federal corporations do not need a licence to carry on business. They file an Initial Return under the Corporations Information Act, with no government fee. Only corporations incorporated outside Canada need an Ontario extra-provincial licence, which costs $330. If expansion is likely, factor extra-provincial registration into your comparison.", parts: ["Within Ontario, corporations from other provinces and federal corporations do not need a licence to carry on business. They file an Initial Return under the Corporations Information Act, with no government fee. Only corporations incorporated outside Canada need an Ontario extra-provincial licence, which costs $330. If expansion is likely, factor ", { text: "extra-provincial registration", href: "/services/extra-provincial" }, " into your comparison."] },

      { type: "heading", id: "worth-it", text: "When the cost is worth it" },
      { type: "paragraph", text: "The government fee is modest. The real question is whether the ongoing cost of running a corporation, mostly accounting, is outweighed by what incorporating gives you." },
      { type: "list", items: ["Limited liability. A corporation is a separate legal person, so its debts and obligations generally belong to it, not to you. Personal guarantees and your own professional liability are exceptions.", "Tax deferral. Active business income kept in the corporation can be taxed at the lower small business rate, and you pay personal tax only when you take money out as salary or dividends.", "Credibility and continuity. Some clients, landlords and lenders prefer to deal with a corporation, and the corporation continues if ownership changes.", "Flexibility. Shares make it easier to bring in partners or investors, or to sell the business later."] },
      { type: "paragraph", text: "Incorporating tends to pay off once the business earns more than you need to live on, or carries real liability risk. If you need every dollar the business earns for personal expenses, the tax deferral does little, and the added accounting cost may outweigh it for now. An accountant can run the numbers for your income. Our guide to the corporate tax rate in Canada explains how the small business rate works.", parts: ["Incorporating tends to pay off once the business earns more than you need to live on, or carries real liability risk. If you need every dollar the business earns for personal expenses, the tax deferral does little, and the added accounting cost may outweigh it for now. An accountant can run the numbers for your income. Our guide to the ", { text: "corporate tax rate in Canada", href: "/guides/corporate-tax-rate-canada" }, " explains how the small business rate works."] },
      { type: "paragraph", text: "When you are ready, you can incorporate in Ontario online with Korporex. The filing, name search, share structure and minute book are handled together, so the price you see covers what you need to start properly. For a step-by-step view of the process itself, see our guide to incorporating in Ontario, or go straight to starting your incorporation.", parts: ["When you are ready, you can ", { text: "incorporate in Ontario online with Korporex", href: "/incorporate" }, ". The filing, name search, share structure and minute book are handled together, so the price you see covers what you need to start properly. For a step-by-step view of the process itself, see our guide to ", { text: "incorporating in Ontario", href: "/guides/incorporating-in-ontario" }, ", or go straight to ", { text: "starting your incorporation", href: "/incorporate" }, "."] },
    ],
    faq: [
      { q: "How much does it cost to incorporate in Ontario?", a: "The Ontario government charges $300 to file Articles of Incorporation, online or by mail. A named corporation also needs an Ontario-biased NUANS report from a private search house, which sets its own price. The Initial Return and annual return have no government fee. On top of that, budget for a minute book and any professional or service fees you choose to pay." },
      { q: "Is a numbered company cheaper to incorporate in Ontario?", a: "Yes, slightly. A numbered corporation such as 1234567 Ontario Inc. does not need a NUANS report, so you pay only the $300 government fee. If you later want to trade under a brand, you can register an operating name for $60, renewed every five years, or change the corporate name by Articles of Amendment for $150 plus a NUANS report." },
      { q: "Is it cheaper to incorporate federally or in Ontario?", a: "The federal filing fee is $200, compared with $300 in Ontario, and federal online incorporation includes the name search for a word name. However, a federal corporation operating in Ontario must also file an Ontario Initial Return and pays a $12 federal annual return each year. For a business that will stay in Ontario, the difference in total cost is small." },
      { q: "Are there annual fees for an Ontario corporation?", a: "The Ontario government charges no fee for the annual return, but filing it is mandatory and a corporation that stops filing can be dissolved. The main yearly cost is the corporate T2 tax return and the accounting behind it. You also keep the minute book current with annual resolutions, and pay for a registered office service if you use one." },
      { q: "Can I incorporate in Ontario without a NUANS report?", a: "Yes, by choosing a numbered corporation. Its name is the Ontario corporation number followed by Ontario and a legal ending such as Inc. A named Ontario corporation always needs an Ontario-biased NUANS report dated no more than 90 days before the articles are filed. A federally biased report is not accepted for an Ontario incorporation." },
      { q: "Do I need a lawyer to incorporate in Ontario?", a: "No. Ontario law does not require a lawyer to file Articles of Incorporation, and you can file directly on the Ontario Business Registry. A lawyer is worth the cost when the setup is not standard, such as several founders, outside investors, a holding company or a professional corporation. For a straightforward corporation, an online service is a common middle ground." },
    ],
  },

  fr: {
    readTime: "12 min de lecture",
    content: [
      { type: "paragraph", text: "Le gouvernement de l'Ontario exige 300 $ pour déposer des statuts constitutifs par le Registre des entreprises de l'Ontario, et ce droit est le même en ligne ou par la poste. C'est le seul droit gouvernemental que toute société ontarienne doit payer. Si vous voulez une société avec un nom, il vous faut aussi un rapport de recherche de nom NUANS axé sur l'Ontario, que vous achetez auprès d'une maison de recherche privée. Le rapport initial et la déclaration annuelle ne comportent aucun droit gouvernemental. Tout le reste, du livre des procès-verbaux à l'aide professionnelle, dépend de vos choix." },
      { type: "paragraph", text: "Ce guide réunit tous les coûts au même endroit : ce que le gouvernement exige, ce qui est optionnel, ce que vous payez une seule fois et ce que vous payez chaque année, et la comparaison avec une constitution fédérale. Tous les droits gouvernementaux ci-dessous ont été vérifiés auprès des barèmes officiels de l'Ontario et de Corporations Canada." },

      { type: "heading", id: "frais-gouvernementaux", text: "Les frais de dépôt gouvernementaux" },
      { type: "paragraph", text: "Le coût de base est le droit de 300 $ pour la constitution en vertu de la Loi sur les sociétés par actions de l'Ontario (LSAO). Vous le payez au Registre des entreprises de l'Ontario au moment de déposer vos statuts constitutifs. En ligne, la constitution est traitée immédiatement. Par la poste, ServiceOntario indique un délai d'environ 15 jours ouvrables. Le droit ne change pas selon le mode de dépôt, si bien que la plupart des gens déposent en ligne." },
      { type: "paragraph", text: "Le droit de dépôt gouvernemental n'est pas assujetti à la TVH. Si vous faites appel à un avocat ou à un service de constitution, la TVH s'applique à ses honoraires ou à ses frais de service, et non aux 300 $ perçus par le gouvernement. L'Ontario n'offre pas de service accéléré payant pour la constitution, puisque les dépôts en ligne sont déjà immédiats." },

      { type: "heading", id: "ventilation-des-frais", text: "La ventilation complète des frais" },
      { type: "paragraph", text: "Voici tous les coûts auxquels une société par actions ontarienne peut s'attendre autour de sa constitution, y compris les dépôts gratuits mais obligatoires. Le droit fédéral figure en bas du tableau à titre de comparaison." },
      {
        type: "table",
        head: ["Élément", "Payé à", "Coût ($ CA)", "Quand"],
        rows: [
          ["Statuts constitutifs (LSAO)", "Registre des entreprises de l'Ontario", "300 $", "Une fois, à la constitution"],
          ["Rapport de recherche de nom NUANS (société avec nom seulement)", "Maison de recherche NUANS privée", "Fixé par la maison de recherche", "Une fois, daté de 90 jours au plus avant le dépôt"],
          ["Rapport initial (Loi sur les renseignements exigés des personnes morales)", "Registre des entreprises de l'Ontario", "0 $", "Dans les 60 jours suivant la constitution"],
          ["Déclaration annuelle (Loi sur les renseignements exigés des personnes morales)", "Registre des entreprises de l'Ontario", "0 $", "Chaque année, dans les six mois suivant la fin de l'exercice"],
          ["Enregistrement d'un nom commercial", "Registre des entreprises de l'Ontario", "60 $", "Seulement si vous exercez sous un autre nom; renouvelé tous les cinq ans"],
          ["Statuts de modification", "Registre des entreprises de l'Ontario", "150 $", "Seulement si vous modifiez vos statuts plus tard"],
          ["Certificat de statut", "Registre des entreprises de l'Ontario", "26 $", "Seulement si une banque, un prêteur ou un acheteur le demande"],
          ["Livre des procès-verbaux", "Préparé par vous ou par un fournisseur", "Aucun droit gouvernemental", "Mis en place une fois, puis tenu à jour"],
          ["Numéro d'entreprise et compte de TPS/TVH", "Agence du revenu du Canada", "0 $", "Lors de l'inscription"],
          ["Statuts constitutifs fédéraux (LCSA), pour comparaison", "Corporations Canada", "200 $", "Une fois, à la constitution"],
        ],
      },
      { type: "callout", title: "Les droits changent", text: "Ce sont les droits officiels publiés par ServiceOntario et Corporations Canada lors de la dernière mise à jour de ce guide. Les droits gouvernementaux sont rajustés de temps à autre; confirmez le barème en vigueur sur le site officiel avant de déposer." },

      { type: "heading", id: "nom-matricule", text: "Nom ou matricule : le rapport NUANS" },
      { type: "paragraph", text: "Si vous voulez une société avec un nom (« Maplewind Conseil Inc. »), il vous faut un rapport de recherche de nom NUANS pour confirmer que le nom est disponible et pas trop semblable à un nom existant. Ce rapport a son propre coût. Une société à matricule (« 1234567 Ontario Inc. ») évite entièrement l'étape NUANS, ce qui est plus rapide et moins cher, le compromis étant que vous avez un numéro plutôt qu'un nom de marque.", parts: ["Si vous voulez une société avec un nom (« Maplewind Conseil Inc. »), il vous faut un ", { text: "rapport de recherche de nom NUANS", href: "/nuans" }, " pour confirmer que le nom est disponible et pas trop semblable à un nom existant. Ce rapport a son propre coût. Une société à matricule (« 1234567 Ontario Inc. ») évite entièrement l'étape NUANS, ce qui est plus rapide et moins cher, le compromis étant que vous avez un numéro plutôt qu'un nom de marque."] },
      { type: "paragraph", text: "L'Ontario impose des règles précises pour ce rapport. Il doit être axé sur l'Ontario, car un rapport axé sur le fédéral n'est pas accepté pour un dépôt ontarien, et il doit être daté de 90 jours au plus avant le dépôt de vos statuts. Le gouvernement de l'Ontario ne vend pas de rapports NUANS. Vous en commandez un auprès d'une maison de recherche privée, qui fixe son propre prix. Si le nom voulu est refusé ou si le rapport expire avant le dépôt, vous devez en payer un nouveau; mieux vaut donc comprendre le fonctionnement d'une recherche NUANS avant de commander.", parts: ["L'Ontario impose des règles précises pour ce rapport. Il doit être axé sur l'Ontario, car un rapport axé sur le fédéral n'est pas accepté pour un dépôt ontarien, et il doit être daté de 90 jours au plus avant le dépôt de vos statuts. Le gouvernement de l'Ontario ne vend pas de rapports NUANS. Vous en commandez un auprès d'une maison de recherche privée, qui fixe son propre prix. Si le nom voulu est refusé ou si le rapport expire avant le dépôt, vous devez en payer un nouveau; mieux vaut donc ", { text: "comprendre le fonctionnement d'une recherche NUANS", href: "/guides/recherche-de-nom-nuans" }, " avant de commander."] },
      { type: "paragraph", text: "Une société à matricule qui veut exercer sous une marque peut enregistrer ce nom commercial en vertu de la Loi sur les noms commerciaux pour 60 $, renouvelable tous les cinq ans. Certains propriétaires commencent avec un matricule pour gagner du temps et économiser, puis choisissent un nom plus tard. Notre guide sur la société nominative ou à matricule explique ce choix.", parts: ["Une société à matricule qui veut exercer sous une marque peut enregistrer ce nom commercial en vertu de la Loi sur les noms commerciaux pour 60 $, renouvelable tous les cinq ans. Certains propriétaires commencent avec un matricule pour gagner du temps et économiser, puis choisissent un nom plus tard. Notre guide sur la ", { text: "société nominative ou à matricule", href: "/guides/societe-nominative-ou-a-matricule" }, " explique ce choix."] },

      { type: "heading", id: "uniques-ou-recurrents", text: "Coûts uniques et coûts récurrents" },
      { type: "paragraph", text: "Il est utile de séparer le budget en deux. Les coûts uniques servent à créer la société et à l'organiser correctement :" },
      { type: "list", items: ["Le droit de 300 $ pour les statuts constitutifs.", "Un rapport NUANS, si vous choisissez une société avec un nom.", "La mise en place du livre des procès-verbaux : règlements administratifs, résolutions d'organisation, souscriptions d'actions et certificats d'actions, et registres de la société.", "Le rapport initial, sans droit gouvernemental, mais à déposer dans les 60 jours suivant la constitution.", "Les honoraires ou frais de service pour préparer et déposer les documents, le cas échéant."] },
      { type: "paragraph", text: "Les coûts récurrents reviennent chaque année tant que la société existe, qu'elle ait des revenus ou non :" },
      { type: "list", items: ["La déclaration annuelle de l'Ontario, gratuite mais obligatoire.", "La déclaration de revenus des sociétés (T2), généralement préparée par un comptable.", "La tenue de livres, que la plupart des sociétés font elles-mêmes avec un logiciel ou confient à quelqu'un.", "Les résolutions annuelles des administrateurs et des actionnaires, conservées dans le livre des procès-verbaux.", "Un service de siège social ou d'adresse, si vous en utilisez un au lieu de votre propre adresse.", "Les frais du compte bancaire d'entreprise, qui varient selon l'institution."] },
      { type: "paragraph", text: "Les coûts uniques sont ce que la plupart des gens comparent en magasinant une constitution. Les coûts récurrents sont ce qui détermine vraiment si la constitution a du sens sur le plan financier; examinez donc les deux avant de décider." },

      { type: "heading", id: "couts-optionnels", text: "Des coûts optionnels à connaître" },
      { type: "list", items: ["Mise en place du livre des procès-verbaux. Les sociétés ontariennes doivent légalement en tenir un. Vous pouvez l'assembler vous-même ou le faire préparer, ce que la plupart des propriétaires trouvent utile.", "Service de siège social ou d'adresse. Si vous ne voulez pas que votre adresse personnelle figure au dossier public, un service d'adresse est un coût additionnel.", "Aide professionnelle. Un avocat ou un service de constitution facture des honoraires en plus du coût gouvernemental, en échange d'une structure d'actions et de documents bien faits.", "Enregistrement d'un nom commercial. 60 $ si vous exercez sous un nom autre que la dénomination légale de la société.", "Certificat de statut. 26 $ lorsqu'une banque, un locateur ou un prêteur demande une preuve que la société est en règle."] },
      { type: "paragraph", text: "Le livre des procès-verbaux mérite qu'on s'y attarde, car c'est souvent le poste que l'on coupe pour économiser. La LSAO oblige toute société à tenir des registres comme ses statuts, ses règlements administratifs, ses procès-verbaux, ses résolutions et ses registres des administrateurs, des actionnaires et des particuliers ayant un contrôle important. Aucun droit gouvernemental ne s'y rattache, mais les documents doivent tout de même être bien rédigés. Un livre des procès-verbaux initial préparé à la constitution coûte moins cher que d'en reconstituer un des années plus tard, quand une banque, un acheteur ou l'ARC demande à le voir. Notre guide du livre des procès-verbaux explique ce qu'il contient.", parts: ["Le livre des procès-verbaux mérite qu'on s'y attarde, car c'est souvent le poste que l'on coupe pour économiser. La LSAO oblige toute société à tenir des registres comme ses statuts, ses règlements administratifs, ses procès-verbaux, ses résolutions et ses registres des administrateurs, des actionnaires et des particuliers ayant un contrôle important. Aucun droit gouvernemental ne s'y rattache, mais les documents doivent tout de même être bien rédigés. Un ", { text: "livre des procès-verbaux initial", href: "/services/initial-minute-book" }, " préparé à la constitution coûte moins cher que d'en reconstituer un des années plus tard, quand une banque, un acheteur ou l'ARC demande à le voir. Notre ", { text: "guide du livre des procès-verbaux", href: "/guides/quest-ce-quun-livre-des-proces-verbaux" }, " explique ce qu'il contient."] },
      { type: "paragraph", text: "Le siège social est l'autre ajout courant. Une société ontarienne doit avoir son siège social à une adresse physique en Ontario, et cette adresse figure au dossier public. Bien des propriétaires qui travaillent de la maison préfèrent un service de siège social pour garder leur adresse personnelle confidentielle.", parts: ["Le siège social est l'autre ajout courant. Une société ontarienne doit avoir son siège social à une adresse physique en Ontario, et cette adresse figure au dossier public. Bien des propriétaires qui travaillent de la maison préfèrent un ", { text: "service de siège social", href: "/services/registered-office" }, " pour garder leur adresse personnelle confidentielle."] },

      { type: "heading", id: "soi-meme-service", text: "Le faire soi-même ou recourir à un service" },
      { type: "paragraph", text: "Il existe trois grandes façons de se constituer en société en Ontario, à trois niveaux de prix différents." },
      { type: "paragraph", text: "Le faire soi-même est l'option la moins coûteuse en argent. Vous déposez directement au Registre des entreprises de l'Ontario et ne payez que le droit gouvernemental, plus un rapport NUANS si vous voulez un nom. En contrepartie, vous rédigez les statuts, choisissez la structure d'actions, préparez les règlements administratifs et les résolutions d'organisation, et montez vous-même le livre des procès-verbaux. Le registre accepte les statuts que vous déposez; il ne vérifie pas si votre structure d'actions convient à votre entreprise." },
      { type: "paragraph", text: "Un service de constitution en ligne coûte plus cher que de le faire soi-même, mais beaucoup moins qu'un cabinet d'avocats à service complet. Un bon service s'occupe du dépôt, de la recherche de nom, d'une structure d'actions adaptée aux situations courantes et du livre des procès-verbaux, à un prix connu d'avance. Korporex constitue les sociétés ontariennes et fédérales en ligne à prix fixe, ce qui comprend le dépôt, la recherche de nom, la structure d'actions et le livre des procès-verbaux, avec livraison des documents en 24 heures.", parts: ["Un service de constitution en ligne coûte plus cher que de le faire soi-même, mais beaucoup moins qu'un cabinet d'avocats à service complet. Un bon service s'occupe du dépôt, de la recherche de nom, d'une structure d'actions adaptée aux situations courantes et du livre des procès-verbaux, à un prix connu d'avance. Korporex constitue les sociétés ontariennes et fédérales en ligne ", { text: "à prix fixe", href: "/order" }, ", ce qui comprend le dépôt, la recherche de nom, la structure d'actions et le livre des procès-verbaux, avec livraison des documents en 24 heures."] },
      { type: "paragraph", text: "L'avocat est la voie la plus coûteuse, et la bonne lorsque la situation n'est pas courante : plusieurs fondateurs qui ont besoin d'une convention d'actionnaires, des investisseurs externes, une structure de société de portefeuille, une société professionnelle, ou une planification fiscale qui dépend des catégories d'actions. Les honoraires varient beaucoup selon le travail requis; demandez une soumission écrite qui distingue les droits gouvernementaux, le rapport NUANS et les honoraires juridiques." },
      { type: "callout", title: "Comparez ce qui est comparable", text: "En comparant des soumissions, vérifiez si le prix comprend le droit gouvernemental de 300 $, le rapport NUANS, le rapport initial et un livre des procès-verbaux complet. Un prix d'appel bas qui exclut le livre des procès-verbaux ou le rapport initial n'est pas l'option la moins chère." },

      { type: "heading", id: "couts-annuels", text: "Ce que cela coûte chaque année ensuite" },
      { type: "paragraph", text: "La constitution n'est pas un coût unique. Chaque année, une société ontarienne produit une déclaration annuelle et une déclaration de revenus des sociétés (T2) distincte, et tient son livre des procès-verbaux à jour. Prévoyez surtout la déclaration de revenus des sociétés, qui implique généralement un comptable.", parts: ["La constitution n'est pas un coût unique. Chaque année, une société ontarienne produit une ", { text: "déclaration annuelle", href: "/guides/declarations-annuelles-societes-canada" }, " et une déclaration de revenus des sociétés (T2) distincte, et tient son livre des procès-verbaux à jour. Prévoyez surtout la déclaration de revenus des sociétés, qui implique généralement un comptable."] },
      { type: "paragraph", text: "La déclaration annuelle de l'Ontario se dépose au Registre des entreprises de l'Ontario dans les six mois suivant la fin de l'exercice de la société. Aucun droit gouvernemental ne s'applique, mais elle n'est pas facultative : une société qui cesse de la produire peut finir par être dissoute. Si vous préférez ne pas surveiller l'échéance, un service de dépôt de la déclaration annuelle de l'Ontario peut s'en charger. La déclaration T2 est transmise à l'Agence du revenu du Canada, qui administre aussi l'impôt des sociétés de l'Ontario; une seule T2 couvre donc les deux. Comme les déclarations de revenus des sociétés et les états financiers sont plus complexes qu'une déclaration personnelle, les honoraires comptables représentent habituellement le plus gros coût récurrent d'une société.", parts: ["La déclaration annuelle de l'Ontario se dépose au Registre des entreprises de l'Ontario dans les six mois suivant la fin de l'exercice de la société. Aucun droit gouvernemental ne s'applique, mais elle n'est pas facultative : une société qui cesse de la produire peut finir par être dissoute. Si vous préférez ne pas surveiller l'échéance, un ", { text: "service de dépôt de la déclaration annuelle de l'Ontario", href: "/services/annual-return-on" }, " peut s'en charger. La déclaration T2 est transmise à l'Agence du revenu du Canada, qui administre aussi l'impôt des sociétés de l'Ontario; une seule T2 couvre donc les deux. Comme les déclarations de revenus des sociétés et les états financiers sont plus complexes qu'une déclaration personnelle, les honoraires comptables représentent habituellement le plus gros coût récurrent d'une société."] },
      { type: "paragraph", text: "Le livre des procès-verbaux exige aussi un suivi annuel. Les administrateurs approuvent les états financiers, les actionnaires nomment un vérificateur ou adoptent une résolution pour s'en dispenser lorsque la loi le permet, et les administrateurs et dirigeants sont confirmés. Ces résolutions annuelles ne coûtent rien à déposer puisqu'elles ne sont déposées nulle part, mais elles doivent être préparées et signées." },

      { type: "heading", id: "couts-oublies", text: "Les coûts qu'on oublie de prévoir" },
      { type: "list", items: ["Les dépôts en retard. La déclaration annuelle est gratuite, mais l'omettre peut mener à la dissolution, et faire reconstituer une société dissoute coûte bien plus cher que de déposer à temps. L'ARC impose des pénalités et des intérêts sur une T2 en retard lorsqu'un impôt est dû.", "Les changements après la constitution. Changer la dénomination ou la structure d'actions exige des statuts de modification, assortis d'un droit gouvernemental de 150 $, plus un nouveau rapport NUANS pour un changement de nom.", "Corriger une mauvaise structure d'actions. Une structure qui ne correspond pas à vos projets peut coûter cher à restructurer plus tard, une fois qu'il y a des actionnaires, des investisseurs ou une planification fiscale à respecter.", "Tenir le dossier public à jour. Les changements d'administrateurs ou de siège social sont déclarés au moyen d'un avis de modification. Le droit gouvernemental est de 0 $, mais quelqu'un doit le déposer.", "Les services bancaires. Les comptes d'entreprise comportent généralement des frais mensuels, et les banques demandent souvent les statuts, le livre des procès-verbaux et parfois un certificat de statut (26 $) pour en ouvrir un."] },
      { type: "paragraph", text: "Aucun de ces coûts n'est important à lui seul. Ensemble, ils expliquent pourquoi le vrai coût d'une société se mesure mieux sur les premières années que le jour du dépôt." },

      { type: "heading", id: "ontario-ou-federal", text: "Ontario ou fédéral : comparaison des coûts" },
      { type: "paragraph", text: "Une société fédérale constituée en vertu de la Loi canadienne sur les sociétés par actions (LCSA) coûte moins cher à déposer, mais la comparaison ne s'arrête pas au droit de dépôt. Voici les deux options côte à côte." },
      {
        type: "table",
        head: ["Poste de coût", "Ontario (LSAO)", "Fédéral (LCSA)"],
        rows: [
          ["Droit de constitution", "300 $", "200 $"],
          ["Recherche de nom", "Rapport NUANS axé sur l'Ontario requis pour une société avec un nom, acheté auprès d'une maison de recherche", "Aucun rapport NUANS distinct requis en ligne pour un nom composé de mots; la recherche fait partie du processus fédéral"],
          ["Traitement accéléré", "Non offert; le dépôt en ligne est immédiat", "100 $ en option, quatre heures ouvrables"],
          ["Déclaration annuelle", "0 $, déposée au Registre des entreprises de l'Ontario", "12 $, déposée auprès de Corporations Canada"],
          ["Statuts de modification", "150 $", "200 $ (certaines modifications sont gratuites)"],
          ["Exercer en Ontario", "Aucun autre dépôt", "Rapport initial en Ontario dans les 60 jours suivant le début des activités en Ontario, 0 $"],
          ["Protection du nom", "Ontario", "Partout au Canada"],
        ],
      },
      { type: "paragraph", text: "Sur le seul plan des droits, une société fédérale coûte moins cher à créer, et la constitution fédérale comprend la recherche de nom pour un nom composé de mots. Une société fédérale qui exerce ses activités en Ontario doit tout de même déposer un rapport initial en Ontario et y tenir ses renseignements à jour, et elle paie chaque année une déclaration annuelle fédérale de 12 $. Si votre entreprise n'exercera qu'en Ontario, la voie ontarienne est plus simple à maintenir. Si vous comptez exercer partout au Canada ou voulez une protection nationale du nom, la voie fédérale en vaut souvent la peine. Notre guide sur la constitution au fédéral ou au provincial compare les deux au-delà du coût.", parts: ["Sur le seul plan des droits, une société fédérale coûte moins cher à créer, et la constitution fédérale comprend la recherche de nom pour un nom composé de mots. Une société fédérale qui exerce ses activités en Ontario doit tout de même déposer un ", { text: "rapport initial en Ontario", href: "/services/initial-return-on" }, " et y tenir ses renseignements à jour, et elle paie chaque année une ", { text: "déclaration annuelle fédérale", href: "/services/annual-return-federal" }, " de 12 $. Si votre entreprise n'exercera qu'en Ontario, la voie ontarienne est plus simple à maintenir. Si vous comptez exercer partout au Canada ou voulez une protection nationale du nom, la voie fédérale en vaut souvent la peine. Notre guide sur la ", { text: "constitution au fédéral ou au provincial", href: "/guides/comment-se-constituer-societe-canada" }, " compare les deux au-delà du coût."] },

      { type: "heading", id: "extraprovincial", text: "Les coûts extraprovinciaux" },
      { type: "paragraph", text: "L'enregistrement extraprovincial s'applique lorsqu'une société exerce des activités hors du ressort où elle a été constituée. Une société ontarienne qui s'étend à une autre province doit s'y enregistrer, et chaque province fixe ses propres droits et dépôts annuels. Une société fédérale doit, elle aussi, s'enregistrer dans chaque province où elle exerce, y compris l'Ontario." },
      { type: "paragraph", text: "En Ontario, les sociétés des autres provinces et les sociétés fédérales n'ont pas besoin de permis pour exercer leurs activités. Elles déposent un rapport initial en vertu de la Loi sur les renseignements exigés des personnes morales, sans droit gouvernemental. Seules les sociétés constituées hors du Canada ont besoin d'un permis extraprovincial de l'Ontario, qui coûte 330 $. Si une expansion est probable, tenez compte de l'enregistrement extraprovincial dans votre comparaison.", parts: ["En Ontario, les sociétés des autres provinces et les sociétés fédérales n'ont pas besoin de permis pour exercer leurs activités. Elles déposent un rapport initial en vertu de la Loi sur les renseignements exigés des personnes morales, sans droit gouvernemental. Seules les sociétés constituées hors du Canada ont besoin d'un permis extraprovincial de l'Ontario, qui coûte 330 $. Si une expansion est probable, tenez compte de ", { text: "l'enregistrement extraprovincial", href: "/services/extra-provincial" }, " dans votre comparaison."] },

      { type: "heading", id: "quand-ca-vaut", text: "Quand le coût en vaut la peine" },
      { type: "paragraph", text: "Le droit gouvernemental est modeste. La vraie question est de savoir si le coût récurrent d'une société, surtout la comptabilité, est compensé par ce que la constitution vous apporte." },
      { type: "list", items: ["La responsabilité limitée. Une société est une personne morale distincte; ses dettes et obligations lui appartiennent donc en général, et non à vous. Les cautionnements personnels et votre propre responsabilité professionnelle font exception.", "Le report d'impôt. Le revenu d'entreprise exploitée activement conservé dans la société peut être imposé au taux réduit des petites entreprises, et vous ne payez l'impôt personnel que lorsque vous retirez des fonds sous forme de salaire ou de dividendes.", "La crédibilité et la continuité. Certains clients, locateurs et prêteurs préfèrent traiter avec une société, et la société continue d'exister si la propriété change.", "La souplesse. Les actions facilitent l'arrivée d'associés ou d'investisseurs, ou la vente de l'entreprise plus tard."] },
      { type: "paragraph", text: "La constitution devient généralement rentable lorsque l'entreprise gagne plus que ce dont vous avez besoin pour vivre, ou comporte un vrai risque de responsabilité. Si vous avez besoin de chaque dollar gagné pour vos dépenses personnelles, le report d'impôt apporte peu, et le coût comptable additionnel peut l'emporter pour l'instant. Un comptable peut faire le calcul selon votre revenu. Notre guide sur le taux d'imposition des sociétés au Canada explique le fonctionnement du taux des petites entreprises.", parts: ["La constitution devient généralement rentable lorsque l'entreprise gagne plus que ce dont vous avez besoin pour vivre, ou comporte un vrai risque de responsabilité. Si vous avez besoin de chaque dollar gagné pour vos dépenses personnelles, le report d'impôt apporte peu, et le coût comptable additionnel peut l'emporter pour l'instant. Un comptable peut faire le calcul selon votre revenu. Notre guide sur le ", { text: "taux d'imposition des sociétés au Canada", href: "/guides/taux-imposition-societes-canada" }, " explique le fonctionnement du taux des petites entreprises."] },
      { type: "paragraph", text: "Lorsque vous êtes prêt, vous pouvez vous constituer en société en Ontario en ligne avec Korporex. Le dépôt, la recherche de nom, la structure d'actions et le livre des procès-verbaux sont traités ensemble, de sorte que le prix affiché couvre ce qu'il faut pour bien démarrer. Pour voir le processus étape par étape, consultez notre guide sur la constitution en Ontario, ou commencez votre constitution dès maintenant.", parts: ["Lorsque vous êtes prêt, vous pouvez ", { text: "vous constituer en société en Ontario en ligne avec Korporex", href: "/incorporate" }, ". Le dépôt, la recherche de nom, la structure d'actions et le livre des procès-verbaux sont traités ensemble, de sorte que le prix affiché couvre ce qu'il faut pour bien démarrer. Pour voir le processus étape par étape, consultez notre guide sur la ", { text: "constitution en Ontario", href: "/guides/se-constituer-en-societe-en-ontario" }, ", ou ", { text: "commencez votre constitution", href: "/incorporate" }, " dès maintenant."] },
    ],
    faq: [
      { q: "Combien coûte la constitution d'une société en Ontario ?", a: "Le gouvernement de l'Ontario exige 300 $ pour déposer des statuts constitutifs, en ligne ou par la poste. Une société avec un nom a aussi besoin d'un rapport NUANS axé sur l'Ontario, acheté auprès d'une maison de recherche privée qui fixe son propre prix. Le rapport initial et la déclaration annuelle ne comportent aucun droit gouvernemental. Prévoyez en plus un livre des procès-verbaux et, s'il y a lieu, des honoraires professionnels." },
      { q: "Une société à matricule coûte-t-elle moins cher en Ontario ?", a: "Oui, un peu. Une société à matricule comme 1234567 Ontario Inc. n'a pas besoin de rapport NUANS; vous ne payez donc que le droit gouvernemental de 300 $. Si vous voulez plus tard exercer sous une marque, vous pouvez enregistrer un nom commercial pour 60 $, renouvelable tous les cinq ans, ou changer la dénomination par statuts de modification pour 150 $, plus un rapport NUANS." },
      { q: "Est-il moins cher de se constituer au fédéral ou en Ontario ?", a: "Le droit de dépôt fédéral est de 200 $, contre 300 $ en Ontario, et la constitution fédérale en ligne comprend la recherche de nom pour un nom composé de mots. Toutefois, une société fédérale qui exerce en Ontario doit aussi y déposer un rapport initial et paie chaque année une déclaration annuelle fédérale de 12 $. Pour une entreprise qui restera en Ontario, l'écart total est faible." },
      { q: "Y a-t-il des frais annuels pour une société ontarienne ?", a: "Le gouvernement de l'Ontario n'exige aucun droit pour la déclaration annuelle, mais son dépôt est obligatoire, et une société qui cesse de la produire peut être dissoute. Le principal coût annuel est la déclaration de revenus T2 et la comptabilité qui la sous-tend. Vous tenez aussi le livre des procès-verbaux à jour par des résolutions annuelles, et payez un service de siège social si vous en utilisez un." },
      { q: "Peut-on se constituer en Ontario sans rapport NUANS ?", a: "Oui, en choisissant une société à matricule. Sa dénomination est le numéro de société ontarien, suivi de « Ontario » et d'un élément juridique comme « Inc. ». Une société ontarienne avec un nom exige toujours un rapport NUANS axé sur l'Ontario, daté de 90 jours au plus avant le dépôt des statuts. Un rapport axé sur le fédéral n'est pas accepté pour une constitution ontarienne." },
      { q: "Faut-il un avocat pour se constituer en société en Ontario ?", a: "Non. La loi ontarienne n'exige pas d'avocat pour déposer des statuts constitutifs, et vous pouvez déposer directement au Registre des entreprises de l'Ontario. Un avocat vaut son coût lorsque la situation n'est pas courante : plusieurs fondateurs, des investisseurs externes, une société de portefeuille ou une société professionnelle. Pour une société simple, un service en ligne est un juste milieu fréquent." },
    ],
  },

  es: {
    readTime: "12 min de lectura",
    content: [
      { type: "paragraph", text: "El gobierno de Ontario cobra $300 por presentar los estatutos de constitución a través del Registro de Empresas de Ontario, y la tarifa es la misma en línea o por correo. Es la única tarifa del gobierno que toda sociedad de Ontario debe pagar. Si quiere una sociedad con nombre, también necesita un informe de búsqueda de nombre NUANS orientado a Ontario, que se compra a una empresa de búsqueda privada. La declaración inicial y la declaración anual no tienen tarifa del gobierno. Todo lo demás, desde el libro de actas hasta la ayuda profesional, depende de sus decisiones." },
      { type: "paragraph", text: "Esta guía reúne todos los costos en un solo lugar: lo que cobra el gobierno, lo que es opcional, lo que paga una sola vez y lo que paga cada año, y cómo se compara el total con una constitución federal. Todas las tarifas del gobierno que aparecen abajo se verificaron con las tablas oficiales de Ontario y de Corporations Canada." },

      { type: "heading", id: "tarifa-gobierno", text: "La tarifa de presentación del gobierno" },
      { type: "paragraph", text: "El costo central es la tarifa de $300 para constituirse bajo la Ley de Sociedades por Acciones de Ontario (OBCA). Se paga al Registro de Empresas de Ontario al presentar los estatutos de constitución. En línea, la constitución se procesa de inmediato. Por correo, ServiceOntario indica un plazo de unos 15 días hábiles. La tarifa no cambia según el método, por lo que la mayoría de las personas presenta en línea." },
      { type: "paragraph", text: "La tarifa de presentación del gobierno no lleva HST. Si recurre a un abogado o a un servicio de constitución, el HST se aplica a sus honorarios o tarifa de servicio, no a los $300 que cobra el gobierno. Ontario no ofrece un servicio exprés pagado para la constitución, porque las presentaciones en línea ya son inmediatas." },

      { type: "heading", id: "desglose-de-tarifas", text: "Desglose completo de tarifas" },
      { type: "paragraph", text: "Estos son todos los costos que puede esperar una sociedad por acciones de Ontario en torno a su constitución, incluidas las presentaciones gratuitas pero obligatorias. La tarifa federal aparece al final como comparación." },
      {
        type: "table",
        head: ["Concepto", "Se paga a", "Costo (CAD)", "Cuándo"],
        rows: [
          ["Estatutos de constitución (OBCA)", "Registro de Empresas de Ontario", "$300", "Una vez, al constituirse"],
          ["Informe de búsqueda de nombre NUANS (solo sociedad con nombre)", "Empresa de búsqueda NUANS privada", "Lo fija la empresa de búsqueda", "Una vez, con fecha de 90 días o menos antes de la presentación"],
          ["Declaración inicial (Ley de Información de Sociedades)", "Registro de Empresas de Ontario", "$0", "Dentro de los 60 días siguientes a la constitución"],
          ["Declaración anual (Ley de Información de Sociedades)", "Registro de Empresas de Ontario", "$0", "Cada año, dentro de los seis meses siguientes al cierre del ejercicio"],
          ["Registro de nombre comercial", "Registro de Empresas de Ontario", "$60", "Solo si opera con otro nombre; se renueva cada cinco años"],
          ["Estatutos de modificación", "Registro de Empresas de Ontario", "$150", "Solo si modifica sus estatutos más adelante"],
          ["Certificado de vigencia (Certificate of Status)", "Registro de Empresas de Ontario", "$26", "Solo si un banco, prestamista o comprador lo pide"],
          ["Libro de actas", "Preparado por usted o por un proveedor", "Sin tarifa del gobierno", "Se monta una vez y luego se mantiene al día"],
          ["Número de negocio y cuenta de GST/HST", "Agencia de Ingresos de Canadá (CRA)", "$0", "Al inscribirse"],
          ["Estatutos de constitución federales (CBCA), como comparación", "Corporations Canada", "$200", "Una vez, al constituirse"],
        ],
      },
      { type: "callout", title: "Las tarifas cambian", text: "Estas son las tarifas oficiales publicadas por ServiceOntario y Corporations Canada en la última actualización de esta guía. Las tarifas del gobierno se ajustan de vez en cuando; confirme la tabla vigente en el sitio oficial antes de presentar." },

      { type: "heading", id: "nombre-numerica", text: "Con nombre o numérica: el informe NUANS" },
      { type: "paragraph", text: "Si quiere una sociedad con nombre («Maplewind Consultoría Inc.»), necesita un informe de búsqueda de nombre NUANS para confirmar que el nombre está disponible y no se confunde con uno existente. Ese informe tiene su propio costo. Una sociedad numérica («1234567 Ontario Inc.») evita por completo el paso NUANS, lo que es más rápido y barato, con la contrapartida de que tiene un número en lugar de un nombre de marca.", parts: ["Si quiere una sociedad con nombre («Maplewind Consultoría Inc.»), necesita un ", { text: "informe de búsqueda de nombre NUANS", href: "/nuans" }, " para confirmar que el nombre está disponible y no se confunde con uno existente. Ese informe tiene su propio costo. Una sociedad numérica («1234567 Ontario Inc.») evita por completo el paso NUANS, lo que es más rápido y barato, con la contrapartida de que tiene un número en lugar de un nombre de marca."] },
      { type: "paragraph", text: "Ontario tiene reglas específicas para el informe. Debe estar orientado a Ontario, porque un informe orientado al ámbito federal no se acepta para una presentación en Ontario, y su fecha no puede ser anterior en más de 90 días a la presentación de los estatutos. El gobierno de Ontario no vende informes NUANS. Se piden a una empresa de búsqueda privada, que fija su propio precio. Si el nombre que quiere es rechazado o el informe vence antes de presentar, tendrá que pagar uno nuevo, así que conviene entender cómo funciona una búsqueda NUANS antes de pedirlo.", parts: ["Ontario tiene reglas específicas para el informe. Debe estar orientado a Ontario, porque un informe orientado al ámbito federal no se acepta para una presentación en Ontario, y su fecha no puede ser anterior en más de 90 días a la presentación de los estatutos. El gobierno de Ontario no vende informes NUANS. Se piden a una empresa de búsqueda privada, que fija su propio precio. Si el nombre que quiere es rechazado o el informe vence antes de presentar, tendrá que pagar uno nuevo, así que conviene ", { text: "entender cómo funciona una búsqueda NUANS", href: "/guides/busqueda-de-nombre-nuans" }, " antes de pedirlo."] },
      { type: "paragraph", text: "Una sociedad numérica que quiera operar con una marca puede registrar ese nombre comercial bajo la Ley de Nombres Comerciales por $60, con renovación cada cinco años. Algunos dueños empiezan con una sociedad numérica para ahorrar tiempo y dinero, y eligen un nombre más adelante. Nuestra guía sobre la sociedad con nombre o numerada explica esa decisión.", parts: ["Una sociedad numérica que quiera operar con una marca puede registrar ese nombre comercial bajo la Ley de Nombres Comerciales por $60, con renovación cada cinco años. Algunos dueños empiezan con una sociedad numérica para ahorrar tiempo y dinero, y eligen un nombre más adelante. Nuestra guía sobre la ", { text: "sociedad con nombre o numerada", href: "/guides/sociedad-con-nombre-o-numerada" }, " explica esa decisión."] },

      { type: "heading", id: "unicos-o-recurrentes", text: "Costos únicos y costos recurrentes" },
      { type: "paragraph", text: "Conviene dividir el presupuesto en dos. Los costos únicos sirven para crear la sociedad y organizarla correctamente:" },
      { type: "list", items: ["La tarifa de $300 por los estatutos de constitución.", "Un informe NUANS, si elige una sociedad con nombre.", "El montaje del libro de actas: reglamentos internos, resoluciones de organización, suscripciones y certificados de acciones, y los registros de la sociedad.", "La declaración inicial, sin tarifa del gobierno pero obligatoria dentro de los 60 días siguientes a la constitución.", "Los honorarios o tarifas de servicio por preparar y presentar los documentos, si los hay."] },
      { type: "paragraph", text: "Los costos recurrentes llegan cada año mientras exista la sociedad, tenga ingresos o no:" },
      { type: "list", items: ["La declaración anual de Ontario, gratuita pero obligatoria.", "La declaración del impuesto de sociedades (T2), que suele preparar un contador.", "La contabilidad diaria, que la mayoría de las sociedades lleva con un programa o encarga a alguien.", "Las resoluciones anuales de los administradores y accionistas, que se guardan en el libro de actas.", "Un servicio de domicilio social o de dirección, si lo usa en lugar de su propia dirección.", "Las comisiones de la cuenta bancaria empresarial, que varían según la institución."] },
      { type: "paragraph", text: "Los costos únicos son lo que la mayoría compara al buscar quién le constituya la sociedad. Los costos recurrentes son los que de verdad determinan si constituirse tiene sentido financiero, así que revise ambos antes de decidir." },

      { type: "heading", id: "costos-opcionales", text: "Costos opcionales que conviene conocer" },
      { type: "list", items: ["Montaje del libro de actas. Las sociedades de Ontario están legalmente obligadas a llevar uno. Puede armarlo usted mismo o hacerlo preparar, lo que la mayoría de los dueños considera que vale la pena.", "Servicio de domicilio social o dirección. Si no quiere que su dirección personal figure en el registro público, un servicio de dirección es un costo adicional.", "Ayuda profesional. Un abogado o servicio de constitución cobra honorarios además del costo del gobierno, a cambio de dejar bien la estructura de acciones y los documentos.", "Registro de nombre comercial. $60 si opera con un nombre distinto de la denominación legal de la sociedad.", "Certificado de vigencia. $26 cuando un banco, arrendador o prestamista pide prueba de que la sociedad está al día."] },
      { type: "paragraph", text: "El libro de actas merece atención especial, porque suele ser la partida que se recorta para ahorrar. La OBCA exige que toda sociedad lleve registros como sus estatutos, reglamentos internos, actas, resoluciones y los registros de administradores, de accionistas y de personas con control significativo. No hay tarifa del gobierno, pero los documentos deben redactarse correctamente. Un libro de actas inicial preparado al constituirse cuesta menos que reconstruirlo años después, cuando un banco, un comprador o la CRA pide verlo. Nuestra guía del libro de actas explica qué contiene.", parts: ["El libro de actas merece atención especial, porque suele ser la partida que se recorta para ahorrar. La OBCA exige que toda sociedad lleve registros como sus estatutos, reglamentos internos, actas, resoluciones y los registros de administradores, de accionistas y de personas con control significativo. No hay tarifa del gobierno, pero los documentos deben redactarse correctamente. Un ", { text: "libro de actas inicial", href: "/services/initial-minute-book" }, " preparado al constituirse cuesta menos que reconstruirlo años después, cuando un banco, un comprador o la CRA pide verlo. Nuestra ", { text: "guía del libro de actas", href: "/guides/que-es-un-libro-de-actas" }, " explica qué contiene."] },
      { type: "paragraph", text: "El domicilio social es el otro añadido frecuente. Una sociedad de Ontario debe tener su domicilio social en una dirección física en Ontario, y esa dirección figura en el registro público. Muchos dueños que trabajan desde casa prefieren un servicio de domicilio social para mantener privada su dirección personal.", parts: ["El domicilio social es el otro añadido frecuente. Una sociedad de Ontario debe tener su domicilio social en una dirección física en Ontario, y esa dirección figura en el registro público. Muchos dueños que trabajan desde casa prefieren un ", { text: "servicio de domicilio social", href: "/services/registered-office" }, " para mantener privada su dirección personal."] },

      { type: "heading", id: "propio-servicio", text: "Hacerlo por su cuenta o usar un servicio" },
      { type: "paragraph", text: "Hay tres formas generales de constituirse en sociedad en Ontario, con tres niveles de precio distintos." },
      { type: "paragraph", text: "Hacerlo por su cuenta es lo más barato en dinero. Presenta directamente ante el Registro de Empresas de Ontario y paga solo la tarifa del gobierno, más un informe NUANS si quiere un nombre. A cambio, usted redacta los estatutos, elige la estructura de acciones, prepara los reglamentos internos y las resoluciones de organización, y monta el libro de actas. El registro acepta los estatutos que presenta; no revisa si su estructura de acciones se ajusta a su negocio." },
      { type: "paragraph", text: "Un servicio de constitución en línea cuesta más que hacerlo por su cuenta, pero bastante menos que un despacho de abogados de servicio completo. Un buen servicio se encarga de la presentación, la búsqueda de nombre, una estructura de acciones adecuada para las situaciones habituales y el libro de actas, por un precio conocido. Korporex constituye sociedades de Ontario y federales en línea por un precio fijo que incluye la presentación, la búsqueda de nombre, la estructura de acciones y el libro de actas, con documentos entregados en 24 horas.", parts: ["Un servicio de constitución en línea cuesta más que hacerlo por su cuenta, pero bastante menos que un despacho de abogados de servicio completo. Un buen servicio se encarga de la presentación, la búsqueda de nombre, una estructura de acciones adecuada para las situaciones habituales y el libro de actas, por un precio conocido. Korporex constituye sociedades de Ontario y federales en línea ", { text: "por un precio fijo", href: "/order" }, " que incluye la presentación, la búsqueda de nombre, la estructura de acciones y el libro de actas, con documentos entregados en 24 horas."] },
      { type: "paragraph", text: "Un abogado es la vía más cara y la correcta cuando la situación no es estándar: varios fundadores que necesitan un convenio de accionistas, inversionistas externos, una estructura con sociedad de cartera, una sociedad profesional o una planificación fiscal que depende de las clases de acciones. Los honorarios varían mucho según el trabajo, así que pida un presupuesto por escrito que separe las tarifas del gobierno, el informe NUANS y los honorarios legales." },
      { type: "callout", title: "Compare lo comparable", text: "Al comparar presupuestos, verifique si el precio incluye la tarifa del gobierno de $300, el informe NUANS, la declaración inicial y un libro de actas completo. Un precio de entrada bajo que deja fuera el libro de actas o la declaración inicial no es la opción más barata." },

      { type: "heading", id: "costos-anuales", text: "Qué cuesta cada año después" },
      { type: "paragraph", text: "Constituirse no es un costo único. Cada año, una sociedad de Ontario presenta una declaración anual y una declaración del impuesto de sociedades (T2) aparte, y mantiene su libro de actas al día. Presupueste sobre todo la declaración del impuesto de sociedades, que suele implicar un contador.", parts: ["Constituirse no es un costo único. Cada año, una sociedad de Ontario presenta una ", { text: "declaración anual", href: "/guides/declaraciones-anuales-sociedades-canada" }, " y una declaración del impuesto de sociedades (T2) aparte, y mantiene su libro de actas al día. Presupueste sobre todo la declaración del impuesto de sociedades, que suele implicar un contador."] },
      { type: "paragraph", text: "La declaración anual de Ontario se presenta ante el Registro de Empresas de Ontario dentro de los seis meses siguientes al cierre del ejercicio de la sociedad. No tiene tarifa del gobierno, pero no es opcional: una sociedad que deja de presentarla puede acabar disuelta. Si prefiere no estar pendiente del plazo, un servicio de presentación de la declaración anual de Ontario puede encargarse. La T2 se presenta a la Agencia de Ingresos de Canadá (CRA), que también administra el impuesto de sociedades de Ontario, de modo que una sola T2 cubre ambos. Como las declaraciones de sociedades y los estados financieros son más complejos que una declaración personal, los honorarios contables suelen ser el mayor costo recurrente de una sociedad.", parts: ["La declaración anual de Ontario se presenta ante el Registro de Empresas de Ontario dentro de los seis meses siguientes al cierre del ejercicio de la sociedad. No tiene tarifa del gobierno, pero no es opcional: una sociedad que deja de presentarla puede acabar disuelta. Si prefiere no estar pendiente del plazo, un ", { text: "servicio de presentación de la declaración anual de Ontario", href: "/services/annual-return-on" }, " puede encargarse. La T2 se presenta a la Agencia de Ingresos de Canadá (CRA), que también administra el impuesto de sociedades de Ontario, de modo que una sola T2 cubre ambos. Como las declaraciones de sociedades y los estados financieros son más complejos que una declaración personal, los honorarios contables suelen ser el mayor costo recurrente de una sociedad."] },
      { type: "paragraph", text: "El libro de actas también necesita mantenimiento anual. Los administradores aprueban los estados financieros, los accionistas nombran un auditor o aprueban una resolución para prescindir de él cuando la ley lo permite, y se confirman los administradores y directivos. Estas resoluciones anuales no cuestan nada en tarifas porque no se presentan ante ningún registro, pero deben prepararse y firmarse." },

      { type: "heading", id: "costos-olvidados", text: "Costos que se suelen olvidar" },
      { type: "list", items: ["Presentaciones tardías. La declaración anual no tiene tarifa, pero omitirla puede llevar a la disolución, y reactivar una sociedad disuelta cuesta mucho más que presentar a tiempo. La CRA cobra multas e intereses sobre una T2 tardía cuando hay impuesto por pagar.", "Cambios después de constituirse. Cambiar la denominación o la estructura de acciones exige estatutos de modificación, con una tarifa del gobierno de $150, más un nuevo informe NUANS si cambia el nombre.", "Corregir una mala estructura de acciones. Una estructura que no se ajusta a sus planes puede costar caro de reorganizar más tarde, cuando ya hay accionistas, inversionistas o planificación fiscal de por medio.", "Mantener al día el registro público. Los cambios de administradores o de domicilio social se comunican con un aviso de cambio. La tarifa del gobierno es $0, pero alguien tiene que presentarlo.", "La banca. Las cuentas empresariales suelen tener comisiones mensuales, y los bancos a menudo piden los estatutos, el libro de actas y a veces un certificado de vigencia ($26) para abrir una."] },
      { type: "paragraph", text: "Ninguno de estos costos es grande por sí solo. Juntos explican por qué el costo real de una sociedad se mide mejor a lo largo de los primeros años que el día en que se presenta." },

      { type: "heading", id: "ontario-o-federal", text: "Ontario o federal: comparación de costos" },
      { type: "paragraph", text: "Una sociedad federal bajo la Ley de Sociedades por Acciones de Canadá (CBCA) es más barata de presentar, pero la comparación no termina en la tarifa de presentación. Así se comparan las dos opciones." },
      {
        type: "table",
        head: ["Concepto", "Ontario (OBCA)", "Federal (CBCA)"],
        rows: [
          ["Tarifa de constitución", "$300", "$200"],
          ["Búsqueda de nombre", "Informe NUANS orientado a Ontario obligatorio para una sociedad con nombre, comprado a una empresa de búsqueda", "No se necesita un informe NUANS aparte en línea para un nombre con palabras; la búsqueda forma parte del proceso federal"],
          ["Tramitación exprés", "No se ofrece; la presentación en línea es inmediata", "$100 opcional, cuatro horas hábiles"],
          ["Declaración anual", "$0, ante el Registro de Empresas de Ontario", "$12, ante Corporations Canada"],
          ["Estatutos de modificación", "$150", "$200 (algunas modificaciones son gratuitas)"],
          ["Operar en Ontario", "Nada más que presentar", "Declaración inicial en Ontario dentro de los 60 días siguientes al inicio de actividades en Ontario, $0"],
          ["Protección del nombre", "Ontario", "Todo Canadá"],
        ],
      },
      { type: "paragraph", text: "Solo por tarifas, una sociedad federal cuesta menos de crear, y la constitución federal incluye la búsqueda de nombre para un nombre con palabras. Aun así, una sociedad federal que opera en Ontario debe presentar una declaración inicial en Ontario y mantener al día allí su información, y paga cada año una declaración anual federal de $12. Si su negocio operará solo en Ontario, la vía de Ontario es más sencilla de mantener. Si piensa operar en todo Canadá o quiere protección nacional del nombre, la vía federal suele compensar. Nuestra guía sobre constitución federal o provincial compara ambas más allá del costo.", parts: ["Solo por tarifas, una sociedad federal cuesta menos de crear, y la constitución federal incluye la búsqueda de nombre para un nombre con palabras. Aun así, una sociedad federal que opera en Ontario debe presentar una ", { text: "declaración inicial en Ontario", href: "/services/initial-return-on" }, " y mantener al día allí su información, y paga cada año una ", { text: "declaración anual federal", href: "/services/annual-return-federal" }, " de $12. Si su negocio operará solo en Ontario, la vía de Ontario es más sencilla de mantener. Si piensa operar en todo Canadá o quiere protección nacional del nombre, la vía federal suele compensar. Nuestra guía sobre ", { text: "constitución federal o provincial", href: "/guides/como-constituirse-sociedad-canada" }, " compara ambas más allá del costo."] },

      { type: "heading", id: "extraprovincial", text: "Costos extraprovinciales" },
      { type: "paragraph", text: "El registro extraprovincial se aplica cuando una sociedad opera fuera de la jurisdicción donde se constituyó. Una sociedad de Ontario que se expande a otra provincia debe registrarse allí, y cada provincia fija sus propias tarifas y presentaciones anuales. Una sociedad federal también debe registrarse en cada provincia donde opera, incluida Ontario." },
      { type: "paragraph", text: "Dentro de Ontario, las sociedades de otras provincias y las sociedades federales no necesitan licencia para operar. Presentan una declaración inicial bajo la Ley de Información de Sociedades, sin tarifa del gobierno. Solo las sociedades constituidas fuera de Canadá necesitan una licencia extraprovincial de Ontario, que cuesta $330. Si es probable que se expanda, tenga en cuenta el registro extraprovincial en su comparación.", parts: ["Dentro de Ontario, las sociedades de otras provincias y las sociedades federales no necesitan licencia para operar. Presentan una declaración inicial bajo la Ley de Información de Sociedades, sin tarifa del gobierno. Solo las sociedades constituidas fuera de Canadá necesitan una licencia extraprovincial de Ontario, que cuesta $330. Si es probable que se expanda, tenga en cuenta el ", { text: "registro extraprovincial", href: "/services/extra-provincial" }, " en su comparación."] },

      { type: "heading", id: "cuando-vale-la-pena", text: "Cuándo vale la pena el costo" },
      { type: "paragraph", text: "La tarifa del gobierno es modesta. La verdadera pregunta es si el costo recurrente de mantener una sociedad, sobre todo la contabilidad, se compensa con lo que la constitución le aporta." },
      { type: "list", items: ["Responsabilidad limitada. Una sociedad es una persona jurídica distinta, por lo que sus deudas y obligaciones son en general suyas y no de usted. Las garantías personales y su propia responsabilidad profesional son excepciones.", "Diferimiento de impuestos. Los ingresos de negocio activo que se quedan en la sociedad pueden tributar a la tasa reducida para pequeñas empresas, y usted paga impuesto personal solo cuando retira dinero como salario o dividendos.", "Credibilidad y continuidad. Algunos clientes, arrendadores y prestamistas prefieren tratar con una sociedad, y la sociedad continúa si cambia la propiedad.", "Flexibilidad. Las acciones facilitan incorporar socios o inversionistas, o vender el negocio más adelante."] },
      { type: "paragraph", text: "Constituirse suele compensar cuando el negocio gana más de lo que usted necesita para vivir, o conlleva un riesgo real de responsabilidad. Si necesita cada dólar que gana el negocio para sus gastos personales, el diferimiento de impuestos aporta poco, y el costo contable adicional puede pesar más por ahora. Un contador puede hacer los números según sus ingresos. Nuestra guía sobre la tasa del impuesto de sociedades en Canadá explica cómo funciona la tasa para pequeñas empresas.", parts: ["Constituirse suele compensar cuando el negocio gana más de lo que usted necesita para vivir, o conlleva un riesgo real de responsabilidad. Si necesita cada dólar que gana el negocio para sus gastos personales, el diferimiento de impuestos aporta poco, y el costo contable adicional puede pesar más por ahora. Un contador puede hacer los números según sus ingresos. Nuestra guía sobre la ", { text: "tasa del impuesto de sociedades en Canadá", href: "/guides/tasa-impuesto-sociedades-canada" }, " explica cómo funciona la tasa para pequeñas empresas."] },
      { type: "paragraph", text: "Cuando esté listo, puede constituirse en sociedad en Ontario en línea con Korporex. La presentación, la búsqueda de nombre, la estructura de acciones y el libro de actas se gestionan juntos, de modo que el precio que ve cubre lo necesario para empezar bien. Para ver el proceso paso a paso, consulte nuestra guía sobre cómo constituirse en sociedad en Ontario, o empiece su constitución ahora.", parts: ["Cuando esté listo, puede ", { text: "constituirse en sociedad en Ontario en línea con Korporex", href: "/incorporate" }, ". La presentación, la búsqueda de nombre, la estructura de acciones y el libro de actas se gestionan juntos, de modo que el precio que ve cubre lo necesario para empezar bien. Para ver el proceso paso a paso, consulte nuestra guía sobre ", { text: "cómo constituirse en sociedad en Ontario", href: "/guides/constituirse-en-sociedad-en-ontario" }, ", o ", { text: "empiece su constitución", href: "/incorporate" }, " ahora."] },
    ],
    faq: [
      { q: "¿Cuánto cuesta constituirse en sociedad en Ontario?", a: "El gobierno de Ontario cobra $300 por presentar los estatutos de constitución, en línea o por correo. Una sociedad con nombre necesita además un informe NUANS orientado a Ontario, que vende una empresa de búsqueda privada con su propio precio. La declaración inicial y la declaración anual no tienen tarifa del gobierno. Además, presupueste un libro de actas y los honorarios profesionales o de servicio que decida pagar." },
      { q: "¿Es más barata una sociedad numérica en Ontario?", a: "Sí, un poco. Una sociedad numérica como 1234567 Ontario Inc. no necesita informe NUANS, así que solo paga la tarifa del gobierno de $300. Si más adelante quiere operar con una marca, puede registrar un nombre comercial por $60, con renovación cada cinco años, o cambiar la denominación mediante estatutos de modificación por $150, más un informe NUANS." },
      { q: "¿Es más barato constituirse a nivel federal o en Ontario?", a: "La tarifa federal es de $200, frente a $300 en Ontario, y la constitución federal en línea incluye la búsqueda de nombre para un nombre con palabras. Sin embargo, una sociedad federal que opera en Ontario también debe presentar allí una declaración inicial y paga cada año una declaración anual federal de $12. Para un negocio que se quedará en Ontario, la diferencia total es pequeña." },
      { q: "¿Hay tarifas anuales para una sociedad de Ontario?", a: "El gobierno de Ontario no cobra por la declaración anual, pero presentarla es obligatorio y una sociedad que deja de hacerlo puede ser disuelta. El principal costo anual es la declaración T2 y la contabilidad que la respalda. También debe mantener el libro de actas al día con resoluciones anuales, y pagar un servicio de domicilio social si lo usa." },
      { q: "¿Puedo constituirme en Ontario sin un informe NUANS?", a: "Sí, eligiendo una sociedad numérica. Su denominación es el número de sociedad de Ontario seguido de Ontario y una terminación legal como Inc. Una sociedad de Ontario con nombre siempre necesita un informe NUANS orientado a Ontario con fecha de 90 días o menos antes de presentar los estatutos. Un informe orientado al ámbito federal no se acepta para una constitución en Ontario." },
      { q: "¿Necesito un abogado para constituirme en sociedad en Ontario?", a: "No. La ley de Ontario no exige un abogado para presentar los estatutos de constitución, y puede presentarlos directamente ante el Registro de Empresas de Ontario. Un abogado vale la pena cuando la situación no es estándar: varios fundadores, inversionistas externos, una sociedad de cartera o una sociedad profesional. Para una sociedad sencilla, un servicio en línea es un término medio habitual." },
    ],
  },
};
