import type { ArticleInline, ArticleSection } from "../articles";

export type ExpandedArticle = { readTime: string; content: ArticleSection[]; faq: { q: string; a: string }[] };

// Builds a paragraph whose plain `text` is always the exact concatenation of
// its parts, so linked and unlinked renderings never drift apart.
function p(...parts: ArticleInline[]): ArticleSection {
  const text = parts.map((x) => (typeof x === "string" ? x : x.text)).join("");
  return parts.some((x) => typeof x !== "string") ? { type: "paragraph", text, parts } : { type: "paragraph", text };
}

const L = (text: string, href: string): ArticleInline => ({ text, href });

export const expanded: Record<"en" | "fr" | "es", ExpandedArticle> = {
  en: {
    readTime: "10 min read",
    content: [
      p("A professional corporation in Ontario is a corporation incorporated or continued under the Ontario Business Corporations Act (OBCA) that holds a valid certificate of authorization from the body that governs a profession. Sections 3.1 to 3.4 of the OBCA set the rules: only professions whose governing Act permits it can practise through one, the shares must be owned by members of the profession (with a family exception for physicians and dentists), the name must include the words \"Professional Corporation\", and the corporation does not limit a professional's personal liability for professional negligence. This guide explains each of those rules, which professions qualify, how the process works, and where tax fits in."),
      p("Outside Ontario, every province has its own version of these rules, set by its corporate statute and its regulators. This guide focuses on Ontario, because that is where the question is most often asked and where the statute is most detailed."),

      { type: "heading", id: "what-it-is", text: "What a professional corporation is" },
      p("Section 3.1 of the OBCA defines a professional corporation as a corporation incorporated or continued under the OBCA that holds a valid certificate of authorization or other authorizing document issued under an Act governing a profession. Both halves matter. A corporation becomes a professional corporation only once it has been incorporated in Ontario and its governing body has authorized it to practise."),
      p("Section 3.2 then says the OBCA and its regulations apply to a professional corporation, except where sections 3.1 to 3.4 and the regulations provide otherwise. In practice, a professional corporation is an ordinary Ontario business corporation with an extra layer of conditions on top. It has directors, officers and shareholders, a registered office, by-laws, a ", L("minute book", "/guides/corporate-minute-book"), " and annual filing obligations, just like any other Ontario corporation. What differs is who can own it, what it can do, what it can be called, and who supervises it."),
      p("The profession stays regulated even when it is practised through a corporation. For health professions, the Health Professions Procedural Code (Schedule 2 to the Regulated Health Professions Act, 1991) states that a member's professional, fiduciary and ethical obligations to patients are not diminished by practising through a health profession corporation, and that they apply equally to the corporation and its directors, officers, shareholders, agents and employees."),

      { type: "heading", id: "who-can-form-one", text: "Which Ontario professions can incorporate" },
      p("Under section 3.1(2) of the OBCA, a professional corporation may practise a profession governed by an Act if that Act expressly permits practice by a corporation, or if the profession is governed by one of the Acts listed in the OBCA itself, or by an Act prescribed by regulation. The listed Acts are:"),
      { type: "table", head: ["Profession", "Governing Act named in OBCA s. 3.1(2)", "Governing body"], rows: [
        ["The 26 regulated health professions, including medicine, dentistry, nursing, pharmacy, optometry, chiropractic, physiotherapy, psychology and massage therapy", "Any Act named in Schedule 1 of the Regulated Health Professions Act, 1991", "The college for that profession, for example the College of Physicians and Surgeons of Ontario (CPSO) or the Royal College of Dental Surgeons of Ontario (RCDSO)"],
        ["Chartered professional accountants", "Chartered Professional Accountants of Ontario Act, 2017", "CPA Ontario"],
        ["Lawyers and paralegals", "Law Society Act", "Law Society of Ontario"],
        ["Social workers and social service workers", "Social Work and Social Service Work Act, 1998", "Ontario College of Social Workers and Social Service Workers"],
        ["Veterinarians", "Veterinarians Act", "College of Veterinarians of Ontario"],
      ] },
      p("The Law Society Act allows a professional corporation for lawyers, one for paralegals (persons licensed to provide legal services), and one owned jointly by lawyers and paralegals. The Health Professions Procedural Code allows one or more members of the same health profession to establish a health profession corporation, subject to the regulations and the college's by-laws. A 2024 amendment will replace the Veterinarians Act in the OBCA list with the Veterinary Professionals Act, 2024, but that change was not yet in force on the current e-Laws consolidation."),
      p("Not every regulated profession uses this structure. Professional engineering, for example, is not on the OBCA list. Under the Professional Engineers Act, a business that offers engineering services to the public needs a certificate of authorization from Professional Engineers Ontario, which can be issued to an individual, a partnership or a corporation. That is a separate regime set by that Act. For any profession, the governing body, not the corporate registry, is the authority on whether and how its members can practise through a corporation."),

      { type: "heading", id: "how-it-differs", text: "How it differs from a regular corporation" },
      p("Section 3.2(2) of the OBCA sets five conditions that every professional corporation must meet, subject to the special health profession rules discussed below:"),
      { type: "list", items: [
        "Ownership. All issued shares must be legally and beneficially owned, directly or indirectly, by one or more members of the same profession.",
        "Directors and officers. All officers and directors must be shareholders of the corporation.",
        "Name. The name must include the words \"Professional Corporation\" or \"société professionnelle\" and must follow both the OBCA name rules and the governing body's name rules.",
        "No number name. A professional corporation cannot be a numbered company.",
        "Restricted business. The articles must provide that the corporation may not carry on any business other than the practice of the profession. Activities related or ancillary to the practice, including investing surplus funds earned by the corporation, are still permitted.",
      ] },
      p("The OBCA adds further safeguards. A voting agreement or proxy that gives a non-shareholder the right to vote a professional corporation's shares is void, and a unanimous shareholder agreement is void unless every shareholder is a member of the profession. A professional corporation also cannot simply lose its status because something happens to a shareholder: under section 3.3, its certificate stays valid despite the death or divorce of a shareholder, the bankruptcy or insolvency of the corporation, or the suspension of the certificate. It ceases to be a professional corporation when the certificate is revoked, and it must then change its name to remove the word \"professional\"."),

      { type: "heading", id: "name-rules", text: "Name requirements" },
      p("Because a professional corporation cannot have a number name, it always needs a word name, and a named Ontario corporation needs an Ontario-biased ", L("NUANS name search report", "/nuans"), " dated within 90 days of filing the articles. The OBCA requirement is only the starting point. Each governing body sets its own name format, and some are strict. The CPSO, for example, requires a physician corporation's name to follow a fixed format, such as \"Smith Medicine Professional Corporation\", using the physician's surname as it appears on the College's register, with no additional words or characters."),
      p("Because of these rules, the proposed name is usually checked against the governing body's requirements before the articles are filed. A name that the corporate registry accepts can still fall short of the governing body's format, and correcting it after incorporation means filing ", L("Articles of Amendment", "/services/articles-amendment"), ". For more on how the search itself works, see our guide to ", L("NUANS name searches", "/guides/what-is-nuans-name-search"), "."),

      { type: "heading", id: "family-shareholders", text: "Share ownership and the family exception" },
      p("The general rule is that only members of the profession can own shares. Lawyers and paralegals follow the Law Society Act version of that rule: shares of a law corporation must be owned by persons licensed to practise law in Ontario, shares of a paralegal corporation by persons licensed to provide legal services, and shares of a combined corporation by persons holding either licence."),
      p("Physicians and dentists have a specific exception. Ontario Regulation 665/05 (Health Profession Corporations) changes the rules for physician corporations and dentist corporations as follows:"),
      { type: "list", items: [
        "Every voting share must be owned, directly or indirectly, by a member of the CPSO (for physicians) or the RCDSO (for dentists).",
        "Non-voting shares may be owned by a member of the college, by a family member of a voting physician or dentist shareholder, or by trustees in trust for that shareholder's minor children.",
        "A family member means the shareholder's spouse, child or parent, as defined in the regulation.",
        "All directors and officers must be shareholders who are members of the college, so family members cannot sit on the board.",
      ] },
      p("Outside those two professions, family members generally cannot hold shares of an Ontario professional corporation under the OBCA rules. Who can own shares has tax consequences as well as regulatory ones, so share structures are usually designed with an accountant or lawyer. Any later change of shareholders also has to be reported. The CPSO, for example, requires notice of changes in shareholders who are members of the College within 15 days."),

      { type: "heading", id: "the-big-misconception", text: "The big misconception about liability" },
      p("People assume a professional corporation shields them from malpractice claims the way a regular corporation shields owners from business debts. It does not. Section 3.4 of the OBCA is explicit. The usual rule that shareholders are not liable for the corporation's obligations does not limit a shareholder's professional liability under the Act governing the profession, for the shareholder's own acts or for the acts of the corporation's employees or agents. The liability of a member for a professional liability claim is not affected by practising through a professional corporation."),
      p("Section 3.4 goes further. Shareholders are jointly and severally liable with the corporation for professional liability claims arising from errors and omissions made while they were shareholders, although no more than they would have been without the corporation. If a professional corporation is a partner in a partnership or limited liability partnership, its shareholders have the same liability as if they were the partners themselves."),
      { type: "callout", text: "Incorporating a practice does not put a wall between a professional and their own professional negligence. That is the single most common misunderstanding about professional corporations. The corporation can still keep ordinary business obligations, such as a supplier contract signed by the corporation, separate from the owner, unless the owner has personally guaranteed them." },

      { type: "heading", id: "federal-or-ontario", text: "Why federal incorporation is not used" },
      p("Many businesses can choose between federal incorporation under the Canada Business Corporations Act (CBCA) and provincial incorporation, as explained in our guide to ", L("federal vs provincial incorporation", "/guides/federal-vs-provincial-incorporation"), ". For an Ontario professional corporation, that choice does not exist in the usual way. The OBCA definition requires the corporation to be incorporated or continued under the OBCA, and the Regulated Health Professions Act, 1991 defines a health profession corporation as a corporation incorporated under the Business Corporations Act. The CPSO states directly that corporations incorporated outside Ontario, including federal CBCA corporations, cannot obtain its certificate of authorization."),
      p("An existing federal corporation is not necessarily a dead end. The OBCA definition covers corporations \"continued\" under the OBCA, so a federal corporation can move to Ontario through a ", L("continuance", "/services/continuance"), " and then meet the professional corporation conditions. Whether that makes sense depends on what the corporation already holds and does."),

      { type: "heading", id: "steps", text: "How to set up a professional corporation in Ontario" },
      p("The exact process depends on the governing body, but the order of steps is broadly the same. The corporation is incorporated first under the OBCA, and the governing body's certificate of authorization follows."),
      { type: "table", head: ["Step", "What happens", "Who is involved"], rows: [
        ["1. Confirm eligibility", "Confirm that the profession can practise through a corporation and review the governing body's requirements for the name, the articles and the application.", "Governing body"],
        ["2. Choose and search the name", "Pick a name that includes \"Professional Corporation\" in the governing body's format, and obtain an Ontario-biased NUANS report dated within 90 days of filing.", "Incorporator, NUANS search house"],
        ["3. Prepare the articles", "Draft Articles of Incorporation with the professional corporation name, a share structure that respects the ownership rules, and the clause restricting the business to the practice of the profession.", "Incorporator, often with a lawyer"],
        ["4. File with Ontario", "File the Articles of Incorporation under the OBCA. The government fee is $300.", "Ontario Business Registry"],
        ["5. Apply for the certificate", "Apply to the governing body for a certificate of authorization, following its application process and paying its fee.", "Governing body"],
        ["6. Organize the corporation", "Adopt by-laws, issue shares only to eligible holders, appoint directors and officers who meet the rules, and set up the minute book.", "Directors and shareholders"],
        ["7. Initial filings", "File the Ontario Initial Return within 60 days of incorporation (no government fee) and register with the CRA for a Business Number and any tax accounts needed.", "Corporation"],
      ] },
      p("After that, the corporation has two sets of ongoing obligations. On the corporate side, it files the Ontario ", L("Initial Return", "/services/initial-return-on"), " once and then an ", L("annual return", "/guides/corporate-annual-returns-canada"), " every year, keeps its minute book current and reports changes of directors or address. On the professional side, it keeps its certificate of authorization valid. The CPSO, for example, requires its certificate to be renewed every year. For the general Ontario incorporation process that sits underneath all of this, see our guide to ", L("incorporating in Ontario", "/guides/incorporating-in-ontario"), "."),

      { type: "heading", id: "why-professionals-incorporate", text: "Why professionals still incorporate: the tax side" },
      p("The main draw is usually tax. A professional corporation that is a Canadian-controlled private corporation can generally claim the small business deduction on its active business income. In 2026, that brings the federal rate down from 15 percent to 9 percent on the first $500,000 of active business income, a limit shared among associated corporations. Provincial tax is added on top. Our guide to ", L("corporate tax rates in Canada", "/guides/corporate-tax-rate-canada"), " sets out the combined rates and the rules that reduce the $500,000 limit."),
      p("The benefit comes from the gap between those corporate rates and the top personal rates. Income left in the corporation is taxed at the corporate rate, and personal tax applies only when the money comes out as salary or dividends, which is why the corporation's ability to invest surplus funds matters. Many professionals compare the options covered in our guide to ", L("salary vs dividends", "/guides/salary-vs-dividends-canada"), "."),
      p("Incorporation is not automatically a tax saving. Professionals who need all their income to live on gain little from deferral, and the income tax rules that limit income splitting with family members apply to professional corporations too, which affects the family share structures allowed for physicians and dentists. The right answer depends on income, family situation and the profession's rules, which is a conversation for an accountant who works with professionals in that field."),

      { type: "heading", id: "where-korporex-fits", text: "Where Korporex fits" },
      p("Korporex's online ", L("incorporation filing", "/incorporate"), " service handles professional corporations the same way as any other incorporation: you complete the online application and Korporex prepares and files the articles. The certificate of authorization from your governing body remains a separate, profession-specific step, and its rules are set by the regulator, not by Korporex. Korporex can provide the Ontario-biased ", L("NUANS report", "/nuans"), " that a professional corporation's name requires. Korporex is not a law firm, and this guide is general information, not legal or tax advice."),
    ],
    faq: [
      { q: "What is a professional corporation in Ontario?", a: "It is a corporation incorporated or continued under the Ontario Business Corporations Act that holds a valid certificate of authorization from the body governing a profession, such as the CPSO or the Law Society of Ontario. It works like a regular Ontario corporation but must meet extra conditions on ownership, directors, its name and the business it can carry on." },
      { q: "Does a professional corporation protect me from malpractice claims?", a: "No. Section 3.4 of the OBCA states that practising through a professional corporation does not affect a member's liability for professional liability claims. Shareholders are also jointly and severally liable with the corporation for claims arising while they were shareholders. The corporation can still separate ordinary business obligations from the owner, unless the owner has personally guaranteed them." },
      { q: "Can my spouse or children own shares of my professional corporation?", a: "Only in specific cases. Under Ontario Regulation 665/05, family members (spouse, child or parent) of a voting shareholder can own non-voting shares of a physician or dentist corporation, and trustees can hold non-voting shares for minor children. For other professions, the OBCA generally requires all shares to be owned by members of the profession. Tax rules on income splitting also apply." },
      { q: "Can I incorporate a professional corporation federally?", a: "Not for an Ontario professional corporation. The OBCA defines a professional corporation as one incorporated or continued under the OBCA, and the CPSO states that federal CBCA corporations cannot obtain its certificate of authorization. An existing federal corporation can be continued into Ontario and then meet the professional corporation requirements." },
      { q: "What name does a professional corporation need?", a: "The name must include \"Professional Corporation\" or \"société professionnelle\", cannot be a number name, and must follow the governing body's format. The CPSO, for example, requires a format like \"Smith Medicine Professional Corporation\" with no additional words. Because it is a named Ontario corporation, an Ontario-biased NUANS report dated within 90 days of filing is required." },
    ],
  },

  fr: {
    readTime: "12 min de lecture",
    content: [
      p("Une société professionnelle en Ontario est une société constituée ou prorogée en vertu de la Loi sur les sociétés par actions de l'Ontario (LSAO) qui détient un certificat d'autorisation valide de l'organisme qui régit une profession. Les articles 3.1 à 3.4 de la LSAO en établissent les règles : seules les professions dont la loi qui les régit le permet peuvent être exercées par son entremise, les actions doivent appartenir à des membres de la profession (avec une exception familiale pour les médecins et les dentistes), la dénomination doit comprendre les mots « société professionnelle » ou « Professional Corporation », et la société ne limite pas la responsabilité personnelle du professionnel pour sa négligence professionnelle. Ce guide explique chacune de ces règles, les professions admissibles, le déroulement du processus et la place de la fiscalité."),
      p("Hors de l'Ontario, chaque province a sa propre version de ces règles, fixée par sa loi sur les sociétés et par ses ordres professionnels. Ce guide porte sur l'Ontario, car c'est là que la question se pose le plus souvent et que la loi est la plus détaillée."),

      { type: "heading", id: "ce-que-cest", text: "Ce qu'est une société professionnelle" },
      p("L'article 3.1 de la LSAO définit la société professionnelle comme une société constituée ou prorogée en vertu de la LSAO qui détient un certificat d'autorisation valide ou un autre document d'autorisation délivré en vertu d'une loi régissant une profession. Les deux éléments comptent. Une société ne devient une société professionnelle qu'une fois constituée en Ontario et autorisée à exercer par son ordre professionnel."),
      p("L'article 3.2 prévoit ensuite que la LSAO et ses règlements s'appliquent à la société professionnelle, sauf disposition contraire des articles 3.1 à 3.4 et des règlements. En pratique, une société professionnelle est une société par actions ontarienne ordinaire à laquelle s'ajoute une couche de conditions. Elle a des administrateurs, des dirigeants et des actionnaires, un siège social, des règlements administratifs, un ", L("livre des procès-verbaux", "/guides/quest-ce-quun-livre-des-proces-verbaux"), " et des obligations de déclaration annuelle, comme toute autre société ontarienne. Ce qui diffère, c'est qui peut en être propriétaire, ce qu'elle peut faire, comment elle peut s'appeler et qui la surveille."),
      p("La profession demeure réglementée même lorsqu'elle est exercée par l'entremise d'une société. Pour les professions de la santé, le Code des professions de la santé (annexe 2 de la Loi de 1991 sur les professions de la santé réglementées) prévoit que les obligations professionnelles, fiduciaires et déontologiques d'un membre envers ses patients ne sont pas diminuées du fait qu'il exerce par l'entremise d'une société professionnelle de la santé, et qu'elles s'appliquent également à la société ainsi qu'à ses administrateurs, dirigeants, actionnaires, mandataires et employés."),

      { type: "heading", id: "qui-peut", text: "Quelles professions ontariennes peuvent se constituer en société" },
      p("Selon le paragraphe 3.1(2) de la LSAO, une société professionnelle peut exercer une profession régie par une loi si cette loi permet expressément l'exercice de la profession par une société, ou si la profession est régie par l'une des lois énumérées dans la LSAO elle-même ou par une loi prescrite par règlement. Les lois énumérées sont les suivantes :"),
      { type: "table", head: ["Profession", "Loi nommée au par. 3.1(2) de la LSAO", "Organisme de réglementation"], rows: [
        ["Les 26 professions de la santé réglementées, dont la médecine, la dentisterie, les soins infirmiers, la pharmacie, l'optométrie, la chiropratique, la physiothérapie, la psychologie et la massothérapie", "Toute loi nommée à l'annexe 1 de la Loi de 1991 sur les professions de la santé réglementées", "L'ordre de la profession, par exemple l'Ordre des médecins et chirurgiens de l'Ontario (OMCO) ou l'Ordre royal des chirurgiens dentistes de l'Ontario (ORCDO)"],
        ["Comptables professionnels agréés", "Loi de 2017 sur les comptables professionnels agréés de l'Ontario", "CPA Ontario"],
        ["Avocats et parajuristes", "Loi sur le Barreau", "Barreau de l'Ontario"],
        ["Travailleurs sociaux et techniciens en travail social", "Loi de 1998 sur le travail social et les techniques de travail social", "Ordre des travailleurs sociaux et des techniciens en travail social de l'Ontario"],
        ["Vétérinaires", "Loi sur les vétérinaires", "Ordre des vétérinaires de l'Ontario"],
      ] },
      p("La Loi sur le Barreau permet une société professionnelle pour les avocats, une pour les parajuristes (les personnes titulaires d'un permis de prestation de services juridiques) et une détenue conjointement par des avocats et des parajuristes. Le Code des professions de la santé permet à un ou plusieurs membres d'une même profession de la santé de constituer une société professionnelle de la santé, sous réserve des règlements et des règlements administratifs de l'ordre. Une modification de 2024 remplacera, dans la liste de la LSAO, la Loi sur les vétérinaires par la Loi de 2024 sur les professionnels vétérinaires, mais ce changement n'était pas encore en vigueur selon la codification actuelle de Lois-en-ligne."),
      p("Ce ne sont pas toutes les professions réglementées qui utilisent cette structure. Le génie, par exemple, ne figure pas sur la liste de la LSAO. Selon la Loi sur les ingénieurs, une entreprise qui offre des services d'ingénierie au public doit détenir un certificat d'autorisation de l'Ordre des ingénieurs de l'Ontario, qui peut être délivré à un particulier, à une société de personnes ou à une société par actions. Il s'agit d'un régime distinct, établi par cette loi. Pour toute profession, c'est l'ordre professionnel, et non le registre des sociétés, qui détermine si et comment ses membres peuvent exercer par l'entremise d'une société."),

      { type: "heading", id: "en-quoi-differe", text: "En quoi elle diffère d'une société ordinaire" },
      p("Le paragraphe 3.2(2) de la LSAO fixe cinq conditions que toute société professionnelle doit remplir, sous réserve des règles particulières aux professions de la santé décrites plus loin :"),
      { type: "list", items: [
        "Propriété. Toutes les actions émises doivent appartenir en propriété légale et bénéficiaire, directement ou indirectement, à un ou plusieurs membres de la même profession.",
        "Administrateurs et dirigeants. Tous les dirigeants et administrateurs doivent être actionnaires de la société.",
        "Dénomination. La dénomination doit comprendre les mots « société professionnelle » ou « Professional Corporation » et respecter à la fois les règles de la LSAO sur les dénominations et celles de l'ordre professionnel.",
        "Pas de dénomination numérique. Une société professionnelle ne peut pas être une société à matricule.",
        "Activité restreinte. Les statuts doivent prévoir que la société ne peut exercer aucune autre activité que l'exercice de la profession. Les activités liées ou accessoires à cet exercice, y compris le placement des fonds excédentaires gagnés par la société, demeurent permises.",
      ] },
      p("La LSAO ajoute d'autres garanties. Une convention de vote ou une procuration qui confère à une personne qui n'est pas actionnaire le droit de voter les actions d'une société professionnelle est nulle, et une convention unanime des actionnaires est nulle à moins que chaque actionnaire ne soit membre de la profession. Une société professionnelle ne perd pas non plus son statut simplement parce qu'un événement touche un actionnaire : selon l'article 3.3, son certificat demeure valide malgré le décès ou le divorce d'un actionnaire, la faillite ou l'insolvabilité de la société, ou la suspension du certificat. Elle cesse d'être une société professionnelle à la révocation du certificat, et doit alors changer sa dénomination pour en retirer le mot « professionnelle »."),

      { type: "heading", id: "denomination", text: "Exigences relatives à la dénomination" },
      p("Comme une société professionnelle ne peut pas avoir de dénomination numérique, elle a toujours besoin d'une dénomination en mots, et une société ontarienne avec dénomination doit obtenir un ", L("rapport de recherche NUANS", "/nuans"), " à portée ontarienne daté d'au plus 90 jours avant le dépôt des statuts. L'exigence de la LSAO n'est qu'un point de départ. Chaque ordre professionnel fixe son propre format, et certains sont stricts. L'OMCO, par exemple, exige que la dénomination d'une société professionnelle de médecins suive un format fixe, comme « Smith Medicine Professional Corporation » ou son équivalent français, en utilisant le nom de famille du médecin tel qu'il figure au tableau de l'Ordre, sans aucun mot ni caractère supplémentaire."),
      p("En raison de ces règles, la dénomination proposée est habituellement vérifiée au regard des exigences de l'ordre avant le dépôt des statuts. Une dénomination acceptée par le registre des sociétés peut quand même ne pas respecter le format de l'ordre, et la corriger après la constitution exige le dépôt de ", L("statuts de modification", "/services/articles-amendment"), ". Pour en savoir plus sur la recherche elle-même, consultez notre guide sur la ", L("recherche de nom NUANS", "/guides/recherche-de-nom-nuans"), "."),

      { type: "heading", id: "actionnaires-famille", text: "Propriété des actions et exception familiale" },
      p("La règle générale veut que seuls les membres de la profession puissent détenir des actions. Les avocats et les parajuristes suivent la version de cette règle prévue par la Loi sur le Barreau : les actions d'une société d'avocats doivent appartenir à des personnes titulaires d'un permis d'exercer le droit en Ontario, celles d'une société de parajuristes à des personnes titulaires d'un permis de prestation de services juridiques, et celles d'une société mixte à des personnes titulaires de l'un ou l'autre permis."),
      p("Les médecins et les dentistes bénéficient d'une exception précise. Le Règlement de l'Ontario 665/05 (Sociétés professionnelles de la santé) modifie les règles applicables aux sociétés professionnelles de médecins et de dentistes comme suit :"),
      { type: "list", items: [
        "Chaque action avec droit de vote doit appartenir, directement ou indirectement, à un membre de l'OMCO (pour les médecins) ou de l'ORCDO (pour les dentistes).",
        "Les actions sans droit de vote peuvent appartenir à un membre de l'ordre, à un membre de la famille d'un médecin ou d'un dentiste actionnaire avec droit de vote, ou à des fiduciaires en fiducie pour les enfants mineurs de cet actionnaire.",
        "Un membre de la famille s'entend du conjoint, de l'enfant ou du père ou de la mère de l'actionnaire, au sens du règlement.",
        "Tous les administrateurs et dirigeants doivent être des actionnaires membres de l'ordre, de sorte que les membres de la famille ne peuvent pas siéger au conseil.",
      ] },
      p("En dehors de ces deux professions, les membres de la famille ne peuvent généralement pas détenir d'actions d'une société professionnelle ontarienne selon les règles de la LSAO. La question de savoir qui peut détenir des actions a des conséquences fiscales autant que réglementaires, de sorte que les structures d'actionnariat sont habituellement conçues avec un comptable ou un avocat. Tout changement ultérieur d'actionnaires doit aussi être déclaré. L'OMCO, par exemple, exige d'être avisé dans les 15 jours de tout changement parmi les actionnaires qui sont membres de l'Ordre."),

      { type: "heading", id: "idee-fausse", text: "La grande idée fausse au sujet de la responsabilité" },
      p("Les gens supposent qu'une société professionnelle les protège des réclamations pour faute professionnelle de la même façon qu'une société ordinaire protège les propriétaires des dettes de l'entreprise. Ce n'est pas le cas. L'article 3.4 de la LSAO est explicite. La règle habituelle selon laquelle les actionnaires ne sont pas responsables des obligations de la société ne limite pas la responsabilité professionnelle d'un actionnaire en vertu de la loi régissant la profession, pour ses propres actes ou pour ceux des employés ou mandataires de la société. La responsabilité d'un membre à l'égard d'une réclamation en responsabilité professionnelle n'est pas touchée par le fait qu'il exerce par l'entremise d'une société professionnelle."),
      p("L'article 3.4 va plus loin. Les actionnaires sont solidairement responsables avec la société des réclamations en responsabilité professionnelle découlant d'erreurs et d'omissions commises pendant qu'ils étaient actionnaires, mais pas davantage qu'ils ne l'auraient été sans la société. Si une société professionnelle est associée d'une société en nom collectif ou d'une société à responsabilité limitée, ses actionnaires ont la même responsabilité que s'ils étaient eux-mêmes les associés."),
      { type: "callout", text: "Constituer une pratique en société n'érige pas un mur entre le professionnel et sa propre négligence professionnelle. C'est le malentendu le plus courant au sujet des sociétés professionnelles. La société peut quand même séparer du propriétaire les obligations commerciales ordinaires, comme un contrat de fournisseur signé par la société, à moins que le propriétaire ne les ait garanties personnellement." },

      { type: "heading", id: "federal-ou-ontario", text: "Pourquoi la constitution fédérale n'est pas utilisée" },
      p("Bien des entreprises peuvent choisir entre la constitution fédérale en vertu de la Loi canadienne sur les sociétés par actions (LCSA) et la constitution provinciale. Pour une société professionnelle ontarienne, ce choix n'existe pas de la façon habituelle. La définition de la LSAO exige que la société soit constituée ou prorogée en vertu de la LSAO, et la Loi de 1991 sur les professions de la santé réglementées définit la société professionnelle de la santé comme une société constituée en vertu de la Loi sur les sociétés par actions. L'OMCO indique expressément que les sociétés constituées hors de l'Ontario, y compris les sociétés fédérales régies par la LCSA, ne peuvent pas obtenir son certificat d'autorisation."),
      p("Une société fédérale existante n'est pas nécessairement une impasse. La définition de la LSAO vise les sociétés « prorogées » en vertu de la LSAO, de sorte qu'une société fédérale peut passer à l'Ontario par une ", L("prorogation", "/services/continuance"), ", puis remplir les conditions applicables aux sociétés professionnelles. L'utilité de cette démarche dépend de ce que la société détient et fait déjà."),

      { type: "heading", id: "etapes", text: "Comment constituer une société professionnelle en Ontario" },
      p("Le processus exact dépend de l'ordre professionnel, mais l'ordre des étapes est sensiblement le même. La société est d'abord constituée en vertu de la LSAO, puis l'ordre professionnel délivre le certificat d'autorisation."),
      { type: "table", head: ["Étape", "Ce qui se passe", "Intervenants"], rows: [
        ["1. Confirmer l'admissibilité", "Confirmer que la profession peut être exercée par une société et examiner les exigences de l'ordre quant à la dénomination, aux statuts et à la demande.", "Ordre professionnel"],
        ["2. Choisir et rechercher la dénomination", "Choisir une dénomination comprenant « société professionnelle » ou « Professional Corporation » dans le format de l'ordre, et obtenir un rapport NUANS à portée ontarienne daté d'au plus 90 jours avant le dépôt.", "Fondateur, maison de recherche NUANS"],
        ["3. Préparer les statuts", "Rédiger les statuts constitutifs avec la dénomination de société professionnelle, une structure d'actions conforme aux règles de propriété et la clause qui limite l'activité à l'exercice de la profession.", "Fondateur, souvent avec un avocat"],
        ["4. Déposer auprès de l'Ontario", "Déposer les statuts constitutifs en vertu de la LSAO. Les droits gouvernementaux sont de 300 $.", "Registre des entreprises de l'Ontario"],
        ["5. Demander le certificat", "Présenter à l'ordre une demande de certificat d'autorisation, selon son processus de demande et en payant les droits qu'il exige.", "Ordre professionnel"],
        ["6. Organiser la société", "Adopter les règlements administratifs, n'émettre des actions qu'aux personnes admissibles, nommer des administrateurs et dirigeants conformes aux règles et constituer le livre des procès-verbaux.", "Administrateurs et actionnaires"],
        ["7. Dépôts initiaux", "Déposer le rapport initial de l'Ontario dans les 60 jours suivant la constitution (sans droits gouvernementaux) et s'inscrire auprès de l'ARC pour obtenir un numéro d'entreprise et les comptes fiscaux nécessaires.", "Société"],
      ] },
      p("Par la suite, la société a deux séries d'obligations continues. Du côté corporatif, elle dépose le ", L("rapport initial", "/services/initial-return-on"), " de l'Ontario une seule fois, puis une ", L("déclaration annuelle", "/guides/declarations-annuelles-societes-canada"), " chaque année, tient son livre des procès-verbaux à jour et déclare les changements d'administrateurs ou d'adresse. Du côté professionnel, elle maintient la validité de son certificat d'autorisation. L'OMCO, par exemple, exige que son certificat soit renouvelé chaque année. Pour le processus général de constitution en Ontario qui sous-tend tout cela, consultez notre guide pour ", L("se constituer en société en Ontario", "/guides/se-constituer-en-societe-en-ontario"), "."),

      { type: "heading", id: "pourquoi", text: "Pourquoi les professionnels se constituent quand même : la fiscalité" },
      p("L'attrait principal est généralement fiscal. Une société professionnelle qui est une société privée sous contrôle canadien peut généralement demander la déduction pour petites entreprises sur son revenu d'entreprise exploitée activement. En 2026, cette déduction fait passer le taux fédéral de 15 % à 9 % sur la première tranche de 500 000 $ de revenu d'entreprise exploitée activement, un plafond partagé entre sociétés associées. L'impôt provincial s'ajoute à ce taux. Notre guide sur les ", L("taux d'imposition des sociétés au Canada", "/guides/taux-imposition-societes-canada"), " présente les taux combinés et les règles qui réduisent le plafond de 500 000 $."),
      p("L'avantage provient de l'écart entre ces taux d'imposition des sociétés et les taux personnels les plus élevés. Le revenu laissé dans la société est imposé au taux de la société, et l'impôt personnel ne s'applique que lorsque l'argent en sort sous forme de salaire ou de dividendes, d'où l'importance de la capacité de la société à placer ses fonds excédentaires. Bien des professionnels comparent les options présentées dans notre guide ", L("salaire ou dividendes", "/guides/salaire-ou-dividendes"), "."),
      p("La constitution en société n'entraîne pas automatiquement une économie d'impôt. Les professionnels qui ont besoin de tout leur revenu pour vivre gagnent peu au report, et les règles fiscales qui limitent le fractionnement du revenu avec les membres de la famille s'appliquent aussi aux sociétés professionnelles, ce qui touche les structures d'actionnariat familial permises aux médecins et aux dentistes. La bonne réponse dépend du revenu, de la situation familiale et des règles de la profession, ce qui est une conversation à avoir avec un comptable qui travaille auprès des professionnels de ce domaine."),

      { type: "heading", id: "ou-korporex", text: "Où se situe Korporex" },
      p("Le service de ", L("dépôt de constitution", "/incorporate"), " en ligne de Korporex traite les sociétés professionnelles comme toute autre constitution : vous remplissez la demande en ligne et Korporex prépare et dépose les statuts. Le certificat d'autorisation de votre ordre professionnel demeure une étape distincte et propre à la profession, dont les règles sont établies par l'ordre, pas par Korporex. Korporex peut fournir le ", L("rapport NUANS", "/nuans"), " à portée ontarienne qu'exige la dénomination d'une société professionnelle. Korporex n'est pas un cabinet d'avocats, et ce guide constitue de l'information générale, et non un avis juridique ou fiscal."),
    ],
    faq: [
      { q: "Qu'est-ce qu'une société professionnelle en Ontario?", a: "C'est une société constituée ou prorogée en vertu de la Loi sur les sociétés par actions de l'Ontario qui détient un certificat d'autorisation valide de l'organisme qui régit une profession, comme l'OMCO ou le Barreau de l'Ontario. Elle fonctionne comme une société ontarienne ordinaire, mais doit respecter des conditions supplémentaires quant à la propriété, aux administrateurs, à la dénomination et à l'activité qu'elle peut exercer." },
      { q: "Une société professionnelle me protège-t-elle des réclamations pour faute professionnelle?", a: "Non. L'article 3.4 de la LSAO prévoit que l'exercice par l'entremise d'une société professionnelle ne touche pas la responsabilité d'un membre à l'égard des réclamations en responsabilité professionnelle. Les actionnaires sont aussi solidairement responsables avec la société des réclamations nées pendant qu'ils étaient actionnaires. La société peut quand même séparer les obligations commerciales ordinaires du propriétaire, sauf garantie personnelle." },
      { q: "Mon conjoint ou mes enfants peuvent-ils détenir des actions de ma société professionnelle?", a: "Seulement dans certains cas. Selon le Règlement de l'Ontario 665/05, les membres de la famille (conjoint, enfant, père ou mère) d'un actionnaire avec droit de vote peuvent détenir des actions sans droit de vote d'une société de médecins ou de dentistes, et des fiduciaires peuvent en détenir pour des enfants mineurs. Pour les autres professions, la LSAO exige généralement que toutes les actions appartiennent à des membres de la profession." },
      { q: "Puis-je constituer une société professionnelle au fédéral?", a: "Pas pour une société professionnelle ontarienne. La LSAO définit la société professionnelle comme une société constituée ou prorogée en vertu de la LSAO, et l'OMCO indique que les sociétés fédérales régies par la LCSA ne peuvent pas obtenir son certificat d'autorisation. Une société fédérale existante peut toutefois être prorogée en Ontario, puis remplir les exigences applicables aux sociétés professionnelles." },
      { q: "Quelle dénomination une société professionnelle doit-elle avoir?", a: "La dénomination doit comprendre « société professionnelle » ou « Professional Corporation », ne peut pas être numérique et doit suivre le format de l'ordre professionnel. L'OMCO, par exemple, exige un format comme « Smith Medicine Professional Corporation », sans mot supplémentaire. Comme il s'agit d'une société ontarienne avec dénomination, un rapport NUANS à portée ontarienne daté d'au plus 90 jours avant le dépôt est requis." },
    ],
  },

  es: {
    readTime: "12 min de lectura",
    content: [
      p("Una sociedad profesional en Ontario es una sociedad constituida o continuada conforme a la Ley de Sociedades por Acciones de Ontario (Ontario Business Corporations Act, OBCA) que tiene un certificado de autorización válido del organismo que rige una profesión. Los artículos 3.1 a 3.4 de la OBCA fijan las reglas: solo las profesiones cuya ley lo permite pueden ejercerse a través de una, las acciones deben pertenecer a miembros de la profesión (con una excepción familiar para médicos y dentistas), la denominación debe incluir las palabras «Professional Corporation» o «société professionnelle», y la sociedad no limita la responsabilidad personal del profesional por su propia negligencia profesional. Esta guía explica cada una de esas reglas, qué profesiones califican, cómo funciona el proceso y qué papel juegan los impuestos."),
      p("Fuera de Ontario, cada provincia tiene su propia versión de estas reglas, fijada por su ley de sociedades y por sus organismos reguladores. Esta guía se centra en Ontario, porque es donde la pregunta surge con más frecuencia y donde la ley es más detallada."),

      { type: "heading", id: "que-es", text: "Qué es una sociedad profesional" },
      p("El artículo 3.1 de la OBCA define la sociedad profesional como una sociedad constituida o continuada conforme a la OBCA que tiene un certificado de autorización válido u otro documento de autorización emitido en virtud de una ley que rige una profesión. Ambas partes importan. Una sociedad se convierte en sociedad profesional solo cuando ha sido constituida en Ontario y su organismo regulador la ha autorizado a ejercer."),
      p("El artículo 3.2 dispone que la OBCA y sus reglamentos se aplican a la sociedad profesional, salvo lo que dispongan en contrario los artículos 3.1 a 3.4 y los reglamentos. En la práctica, una sociedad profesional es una sociedad por acciones ordinaria de Ontario con una capa adicional de condiciones. Tiene administradores, directivos y accionistas, un domicilio social, reglamentos internos, un ", L("libro de actas", "/guides/que-es-un-libro-de-actas"), " y obligaciones de declaración anual, como cualquier otra sociedad de Ontario. Lo que cambia es quién puede ser propietario, qué puede hacer, cómo puede llamarse y quién la supervisa."),
      p("La profesión sigue regulada aunque se ejerza a través de una sociedad. En las profesiones de la salud, el Código de Procedimiento de las Profesiones de la Salud (anexo 2 de la Ley de Profesiones de la Salud Reguladas de 1991) establece que las obligaciones profesionales, fiduciarias y éticas de un miembro hacia sus pacientes no disminuyen por ejercer a través de una sociedad profesional de la salud, y que se aplican por igual a la sociedad y a sus administradores, directivos, accionistas, agentes y empleados."),

      { type: "heading", id: "quien-puede", text: "Qué profesiones de Ontario pueden constituirse en sociedad" },
      p("Según el apartado 3.1(2) de la OBCA, una sociedad profesional puede ejercer una profesión regida por una ley si esa ley permite expresamente el ejercicio de la profesión por una sociedad, o si la profesión está regida por una de las leyes enumeradas en la propia OBCA o por una ley prescrita por reglamento. Las leyes enumeradas son:"),
      { type: "table", head: ["Profesión", "Ley nombrada en el art. 3.1(2) de la OBCA", "Organismo regulador"], rows: [
        ["Las 26 profesiones de la salud reguladas, entre ellas medicina, odontología, enfermería, farmacia, optometría, quiropráctica, fisioterapia, psicología y masoterapia", "Cualquier ley nombrada en el anexo 1 de la Ley de Profesiones de la Salud Reguladas de 1991", "El colegio de esa profesión, por ejemplo el College of Physicians and Surgeons of Ontario (CPSO) o el Royal College of Dental Surgeons of Ontario (RCDSO)"],
        ["Contadores públicos colegiados (CPA)", "Chartered Professional Accountants of Ontario Act, 2017", "CPA Ontario"],
        ["Abogados y paralegales", "Law Society Act", "Law Society of Ontario"],
        ["Trabajadores sociales y técnicos en trabajo social", "Social Work and Social Service Work Act, 1998", "Ontario College of Social Workers and Social Service Workers"],
        ["Veterinarios", "Veterinarians Act", "College of Veterinarians of Ontario"],
      ] },
      p("La Law Society Act permite una sociedad profesional para abogados, una para paralegales (personas con licencia para prestar servicios jurídicos) y una propiedad conjunta de abogados y paralegales. El Código de Procedimiento de las Profesiones de la Salud permite que uno o más miembros de una misma profesión de la salud constituyan una sociedad profesional de la salud, sujeto a los reglamentos y a los reglamentos internos del colegio. Una reforma de 2024 sustituirá en la lista de la OBCA la Veterinarians Act por la Veterinary Professionals Act, 2024, pero ese cambio todavía no estaba en vigor según la consolidación actual de e-Laws."),
      p("No todas las profesiones reguladas usan esta estructura. La ingeniería, por ejemplo, no figura en la lista de la OBCA. Según la Professional Engineers Act, un negocio que ofrece servicios de ingeniería al público necesita un certificado de autorización de Professional Engineers Ontario, que puede emitirse a una persona física, a una sociedad de personas o a una sociedad por acciones. Es un régimen distinto, fijado por esa ley. Para cualquier profesión, el organismo regulador, y no el registro de sociedades, es la autoridad para determinar si sus miembros pueden ejercer a través de una sociedad y cómo."),

      { type: "heading", id: "en-que-difiere", text: "En qué se diferencia de una sociedad normal" },
      p("El apartado 3.2(2) de la OBCA fija cinco condiciones que toda sociedad profesional debe cumplir, sujeto a las reglas especiales para las profesiones de la salud que se explican más adelante:"),
      { type: "list", items: [
        "Titularidad. Todas las acciones emitidas deben pertenecer legal y beneficiariamente, directa o indirectamente, a uno o más miembros de la misma profesión.",
        "Administradores y directivos. Todos los directivos y administradores deben ser accionistas de la sociedad.",
        "Denominación. La denominación debe incluir las palabras «Professional Corporation» o «société professionnelle» y cumplir tanto las reglas de denominación de la OBCA como las del organismo regulador.",
        "Sin denominación numérica. Una sociedad profesional no puede ser una sociedad numerada.",
        "Actividad restringida. Los estatutos deben disponer que la sociedad no puede realizar ninguna actividad distinta del ejercicio de la profesión. Las actividades relacionadas o accesorias a ese ejercicio, incluida la inversión de los fondos excedentes generados por la sociedad, siguen permitidas.",
      ] },
      p("La OBCA añade otras salvaguardas. Un acuerdo de voto o un poder que otorgue a alguien que no es accionista el derecho a votar las acciones de una sociedad profesional es nulo, y un acuerdo unánime de accionistas es nulo salvo que cada accionista sea miembro de la profesión. Una sociedad profesional tampoco pierde su condición solo porque algo le ocurra a un accionista: según el artículo 3.3, su certificado sigue siendo válido pese al fallecimiento o divorcio de un accionista, la quiebra o insolvencia de la sociedad o la suspensión del certificado. Deja de ser sociedad profesional cuando se revoca el certificado, y entonces debe cambiar su denominación para eliminar la palabra «professional»."),

      { type: "heading", id: "denominacion", text: "Requisitos de la denominación" },
      p("Como una sociedad profesional no puede tener denominación numérica, siempre necesita una denominación con palabras, y una sociedad de Ontario con denominación necesita un ", L("informe de búsqueda NUANS", "/nuans"), " con enfoque en Ontario fechado dentro de los 90 días anteriores a la presentación de los estatutos. El requisito de la OBCA es solo el punto de partida. Cada organismo regulador fija su propio formato, y algunos son estrictos. El CPSO, por ejemplo, exige que la denominación de una sociedad profesional de médicos siga un formato fijo, como «Smith Medicine Professional Corporation», usando el apellido del médico tal como figura en el registro del colegio, sin palabras ni caracteres adicionales."),
      p("Por estas reglas, la denominación propuesta suele verificarse frente a los requisitos del organismo regulador antes de presentar los estatutos. Una denominación que el registro de sociedades acepta puede no cumplir el formato del regulador, y corregirla después de la constitución exige presentar ", L("estatutos de modificación", "/services/articles-amendment"), ". Para saber más sobre cómo funciona la búsqueda, consulte nuestra guía sobre la ", L("búsqueda de nombre NUANS", "/guides/busqueda-de-nombre-nuans"), "."),

      { type: "heading", id: "accionistas-familia", text: "Titularidad de las acciones y la excepción familiar" },
      p("La regla general es que solo los miembros de la profesión pueden tener acciones. Los abogados y paralegales siguen la versión de esa regla de la Law Society Act: las acciones de una sociedad de abogados deben pertenecer a personas con licencia para ejercer el derecho en Ontario, las de una sociedad de paralegales a personas con licencia para prestar servicios jurídicos, y las de una sociedad mixta a personas con cualquiera de las dos licencias."),
      p("Los médicos y dentistas tienen una excepción específica. El Reglamento de Ontario 665/05 (Health Profession Corporations) modifica las reglas para las sociedades de médicos y de dentistas de la siguiente manera:"),
      { type: "list", items: [
        "Cada acción con derecho a voto debe pertenecer, directa o indirectamente, a un miembro del CPSO (para médicos) o del RCDSO (para dentistas).",
        "Las acciones sin derecho a voto pueden pertenecer a un miembro del colegio, a un familiar de un médico o dentista accionista con derecho a voto, o a fiduciarios en fideicomiso para los hijos menores de ese accionista.",
        "Familiar significa el cónyuge, hijo, padre o madre del accionista, según las definiciones del reglamento.",
        "Todos los administradores y directivos deben ser accionistas miembros del colegio, por lo que los familiares no pueden formar parte del consejo.",
      ] },
      p("Fuera de esas dos profesiones, los familiares por lo general no pueden tener acciones de una sociedad profesional de Ontario según las reglas de la OBCA. Quién puede tener acciones tiene consecuencias fiscales además de regulatorias, por lo que las estructuras accionariales suelen diseñarse con un contador o un abogado. Cualquier cambio posterior de accionistas también debe notificarse. El CPSO, por ejemplo, exige aviso dentro de los 15 días de cualquier cambio en los accionistas que sean miembros del colegio."),

      { type: "heading", id: "idea-equivocada", text: "La gran idea equivocada sobre la responsabilidad" },
      p("La gente supone que una sociedad profesional la protege de reclamaciones por negligencia profesional del mismo modo que una sociedad normal protege a los propietarios de las deudas del negocio. No es así. El artículo 3.4 de la OBCA es explícito. La regla habitual de que los accionistas no responden de las obligaciones de la sociedad no limita la responsabilidad profesional de un accionista conforme a la ley que rige la profesión, por sus propios actos o por los actos de los empleados o agentes de la sociedad. La responsabilidad de un miembro por una reclamación de responsabilidad profesional no se ve afectada por ejercer a través de una sociedad profesional."),
      p("El artículo 3.4 va más allá. Los accionistas son responsables solidariamente con la sociedad de las reclamaciones de responsabilidad profesional derivadas de errores y omisiones cometidos mientras eran accionistas, aunque no más de lo que lo habrían sido sin la sociedad. Si una sociedad profesional es socia de una sociedad de personas o de una sociedad de responsabilidad limitada, sus accionistas tienen la misma responsabilidad que si fueran ellos mismos los socios."),
      { type: "callout", text: "Constituir una práctica en sociedad no levanta un muro entre el profesional y su propia negligencia profesional. Ese es el malentendido más común sobre las sociedades profesionales. La sociedad sí puede separar del propietario las obligaciones comerciales ordinarias, como un contrato con un proveedor firmado por la sociedad, salvo que el propietario las haya garantizado personalmente." },

      { type: "heading", id: "federal-u-ontario", text: "Por qué no se usa la constitución federal" },
      p("Muchas empresas pueden elegir entre la constitución federal conforme a la Ley de Sociedades por Acciones de Canadá (CBCA) y la constitución provincial. Para una sociedad profesional de Ontario, esa elección no existe de la forma habitual. La definición de la OBCA exige que la sociedad esté constituida o continuada conforme a la OBCA, y la Ley de Profesiones de la Salud Reguladas de 1991 define la sociedad profesional de la salud como una sociedad constituida conforme a la Business Corporations Act. El CPSO indica expresamente que las sociedades constituidas fuera de Ontario, incluidas las sociedades federales de la CBCA, no pueden obtener su certificado de autorización."),
      p("Una sociedad federal existente no es necesariamente un callejón sin salida. La definición de la OBCA abarca las sociedades «continuadas» conforme a la OBCA, de modo que una sociedad federal puede trasladarse a Ontario mediante una ", L("continuación", "/services/continuance"), " y luego cumplir las condiciones de sociedad profesional. Que eso tenga sentido depende de lo que la sociedad ya tiene y hace."),

      { type: "heading", id: "pasos", text: "Cómo constituir una sociedad profesional en Ontario" },
      p("El proceso exacto depende del organismo regulador, pero el orden de los pasos es en general el mismo. Primero se constituye la sociedad conforme a la OBCA y después el organismo regulador emite el certificado de autorización."),
      { type: "table", head: ["Paso", "Qué ocurre", "Quién interviene"], rows: [
        ["1. Confirmar la elegibilidad", "Confirmar que la profesión puede ejercerse a través de una sociedad y revisar los requisitos del regulador sobre la denominación, los estatutos y la solicitud.", "Organismo regulador"],
        ["2. Elegir y buscar la denominación", "Elegir una denominación que incluya «Professional Corporation» en el formato del regulador y obtener un informe NUANS con enfoque en Ontario fechado dentro de los 90 días anteriores a la presentación.", "Fundador, empresa de búsqueda NUANS"],
        ["3. Preparar los estatutos", "Redactar los estatutos de constitución con la denominación de sociedad profesional, una estructura de acciones que respete las reglas de titularidad y la cláusula que limita la actividad al ejercicio de la profesión.", "Fundador, a menudo con un abogado"],
        ["4. Presentar ante Ontario", "Presentar los estatutos de constitución conforme a la OBCA. La tasa gubernamental es de $300.", "Ontario Business Registry"],
        ["5. Solicitar el certificado", "Solicitar al organismo regulador un certificado de autorización, siguiendo su proceso de solicitud y pagando su tarifa.", "Organismo regulador"],
        ["6. Organizar la sociedad", "Adoptar los reglamentos internos, emitir acciones solo a titulares elegibles, nombrar administradores y directivos que cumplan las reglas y preparar el libro de actas.", "Administradores y accionistas"],
        ["7. Presentaciones iniciales", "Presentar la declaración inicial de Ontario dentro de los 60 días siguientes a la constitución (sin tasa gubernamental) e inscribirse ante la CRA para obtener un número de negocio y las cuentas fiscales necesarias.", "Sociedad"],
      ] },
      p("Después, la sociedad tiene dos conjuntos de obligaciones continuas. En el plano societario, presenta la ", L("declaración inicial", "/services/initial-return-on"), " de Ontario una sola vez y luego una ", L("declaración anual", "/guides/declaraciones-anuales-sociedades-canada"), " cada año, mantiene su libro de actas al día e informa los cambios de administradores o de dirección. En el plano profesional, mantiene vigente su certificado de autorización. El CPSO, por ejemplo, exige renovar su certificado cada año. Para el proceso general de constitución en Ontario que está detrás de todo esto, consulte nuestra guía para ", L("constituirse en sociedad en Ontario", "/guides/constituirse-en-sociedad-en-ontario"), "."),

      { type: "heading", id: "por-que", text: "Por qué los profesionales se constituyen de todos modos: el aspecto fiscal" },
      p("El atractivo principal suele ser fiscal. Una sociedad profesional que es una sociedad privada bajo control canadiense (CCPC) generalmente puede aplicar la deducción para pequeñas empresas sobre sus ingresos de negocio activo. En 2026, esa deducción reduce la tasa federal del 15 por ciento al 9 por ciento sobre los primeros $500,000 de ingresos de negocio activo, un límite compartido entre sociedades asociadas. El impuesto provincial se suma a esa tasa. Nuestra guía sobre las ", L("tasas del impuesto de sociedades en Canadá", "/guides/tasa-impuesto-sociedades-canada"), " presenta las tasas combinadas y las reglas que reducen el límite de $500,000."),
      p("El beneficio proviene de la diferencia entre esas tasas de sociedades y las tasas personales más altas. Los ingresos que se dejan en la sociedad tributan a la tasa de la sociedad, y el impuesto personal solo se aplica cuando el dinero sale como salario o dividendos, por eso importa que la sociedad pueda invertir sus fondos excedentes. Muchos profesionales comparan las opciones que explica nuestra guía sobre ", L("salario o dividendos", "/guides/salario-o-dividendos"), "."),
      p("Constituirse en sociedad no supone automáticamente un ahorro fiscal. Los profesionales que necesitan todos sus ingresos para vivir ganan poco con el diferimiento, y las reglas fiscales que limitan la división de ingresos con familiares también se aplican a las sociedades profesionales, lo que afecta a las estructuras accionariales familiares permitidas a médicos y dentistas. La respuesta correcta depende de los ingresos, la situación familiar y las reglas de la profesión, lo cual es una conversación para un contador que trabaje con profesionales de ese ámbito."),

      { type: "heading", id: "donde-korporex", text: "Dónde encaja Korporex" },
      p("El servicio de ", L("presentación de la constitución", "/incorporate"), " en línea de Korporex gestiona las sociedades profesionales igual que cualquier otra constitución: usted completa la solicitud en línea y Korporex prepara y presenta los estatutos. El certificado de autorización de su organismo regulador sigue siendo un paso aparte y propio de la profesión, cuyas reglas fija el regulador, no Korporex. Korporex puede proporcionar el ", L("informe NUANS", "/nuans"), " con enfoque en Ontario que exige la denominación de una sociedad profesional. Korporex no es un despacho de abogados, y esta guía es información general, no asesoramiento jurídico ni fiscal."),
    ],
    faq: [
      { q: "¿Qué es una sociedad profesional en Ontario?", a: "Es una sociedad constituida o continuada conforme a la Ley de Sociedades por Acciones de Ontario que tiene un certificado de autorización válido del organismo que rige una profesión, como el CPSO o la Law Society of Ontario. Funciona como una sociedad ordinaria de Ontario, pero debe cumplir condiciones adicionales sobre la titularidad, los administradores, la denominación y la actividad que puede realizar." },
      { q: "¿Una sociedad profesional me protege de las reclamaciones por negligencia profesional?", a: "No. El artículo 3.4 de la OBCA establece que ejercer a través de una sociedad profesional no afecta la responsabilidad de un miembro por reclamaciones de responsabilidad profesional. Los accionistas además responden solidariamente con la sociedad de las reclamaciones surgidas mientras eran accionistas. La sociedad sí puede separar del propietario las obligaciones comerciales ordinarias, salvo garantía personal." },
      { q: "¿Mi cónyuge o mis hijos pueden tener acciones de mi sociedad profesional?", a: "Solo en casos concretos. Según el Reglamento de Ontario 665/05, los familiares (cónyuge, hijo, padre o madre) de un accionista con derecho a voto pueden tener acciones sin derecho a voto de una sociedad de médicos o dentistas, y unos fiduciarios pueden tenerlas para hijos menores. Para otras profesiones, la OBCA exige en general que todas las acciones pertenezcan a miembros de la profesión." },
      { q: "¿Puedo constituir una sociedad profesional a nivel federal?", a: "No para una sociedad profesional de Ontario. La OBCA define la sociedad profesional como una constituida o continuada conforme a la OBCA, y el CPSO indica que las sociedades federales de la CBCA no pueden obtener su certificado de autorización. Una sociedad federal existente sí puede continuarse en Ontario y después cumplir los requisitos de sociedad profesional." },
      { q: "¿Qué denominación necesita una sociedad profesional?", a: "La denominación debe incluir «Professional Corporation» o «société professionnelle», no puede ser numérica y debe seguir el formato del organismo regulador. El CPSO, por ejemplo, exige un formato como «Smith Medicine Professional Corporation», sin palabras adicionales. Como es una sociedad de Ontario con denominación, se requiere un informe NUANS con enfoque en Ontario fechado dentro de los 90 días anteriores a la presentación." },
    ],
  },
};
